cmake_minimum_required(VERSION 3.28)
project(C11_Networking_Service_Design LANGUAGES CXX)
include(cmake/StudySetup.cmake)
add_subdirectory(L01_framing)
add_subdirectory(L02_connections)
add_subdirectory(L03_transport)
add_subdirectory(L04_native_io)
add_subdirectory(L05_tasks)
add_subdirectory(L06_asio)
add_subdirectory(L07_tls)
add_subdirectory(L08_http2)
add_subdirectory(L09_quic)
add_subdirectory(L10_service_policy)
add_subdirectory(P1_task_service)
add_subdirectory(P2_grpc)
add_subdirectory(L11_bridges)
add_subdirectory(B01_pool_cost)
learncpp_setup_ide("")
