include_guard(GLOBAL)
set(C10_STDEXEC_REVISION "6d7ad689f4d4831c5136e4abe1c601f9a3b64e43")
set(FETCHCONTENT_SOURCE_DIR_STDEXEC "" CACHE PATH "Local pinned stdexec checkout; configuration never downloads")
if(NOT FETCHCONTENT_SOURCE_DIR_STDEXEC AND EXISTS "${CMAKE_CURRENT_LIST_DIR}/../third_party/stdexec/include/stdexec/execution.hpp")
    get_filename_component(FETCHCONTENT_SOURCE_DIR_STDEXEC "${CMAKE_CURRENT_LIST_DIR}/../third_party/stdexec" ABSOLUTE)
endif()
if(NOT EXISTS "${FETCHCONTENT_SOURCE_DIR_STDEXEC}/include/stdexec/execution.hpp")
    message(FATAL_ERROR "Provide -DFETCHCONTENT_SOURCE_DIR_STDEXEC=<local nvhpc-26.05 checkout>. See BUILD_GUIDE.md. No download attempted.")
endif()
find_package(Git REQUIRED)
execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${FETCHCONTENT_SOURCE_DIR_STDEXEC}" rev-parse HEAD
    RESULT_VARIABLE revision_result OUTPUT_VARIABLE revision OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT revision_result EQUAL 0 OR NOT revision STREQUAL C10_STDEXEC_REVISION)
    message(FATAL_ERROR "C10 requires stdexec ${C10_STDEXEC_REVISION}; actual=${revision}")
endif()
execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${FETCHCONTENT_SOURCE_DIR_STDEXEC}" diff --quiet HEAD -- include src
    RESULT_VARIABLE dirty_result)
if(NOT dirty_result EQUAL 0)
    message(FATAL_ERROR "stdexec include/src differ from the pinned revision")
endif()
find_package(Threads REQUIRED)
add_library(c10_stdexec INTERFACE)
add_library(stdexec::stdexec ALIAS c10_stdexec)
target_include_directories(c10_stdexec SYSTEM INTERFACE "${FETCHCONTENT_SOURCE_DIR_STDEXEC}/include")
target_link_libraries(c10_stdexec INTERFACE Threads::Threads)
if(MSVC)
    target_compile_options(c10_stdexec INTERFACE /Zc:__cplusplus /Zc:preprocessor /Zc:externConstexpr /bigobj)
endif()
message(STATUS "C10 stdexec: ${revision} (local headers, no upstream CMake/download)")
