include_guard(GLOBAL)
include(CTest)
include("${CMAKE_CURRENT_LIST_DIR}/StdexecSetup.cmake")
find_package(Python3 3.10 REQUIRED COMPONENTS Interpreter)
find_package(Threads REQUIRED)
get_filename_component(C10_EXERCISES "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
get_filename_component(C10_REPO "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
option(C10_STUDY_BUILD_REFERENCE "Build independent Reference and checker controls" ON)
option(C10_STUDY_TEST_STUDENTS "Register students: unfinished remains a failure" OFF)
option(C10_STUDY_ENABLE_ASAN "Address sanitizer" OFF)
option(C10_STUDY_ENABLE_UBSAN "Undefined behavior sanitizer (separate compiler capability)" OFF)
option(C10_STUDY_ENABLE_TSAN "Thread sanitizer in a separate supported build" OFF)
option(C10_STUDY_TRACE_INCLUDES "Capture actual selected implementation headers" OFF)
option(C10_STUDY_ENABLE_IO_URING "Enable the fixed local liburing backend" OFF)
set(C10_LIBURING_ROOT "" CACHE PATH "Existing liburing 2.15 prefix with C07 source commit marker")
if(C10_STUDY_ENABLE_IO_URING)
    if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
        message(FATAL_ERROR "io_uring is a Linux backend")
    endif()
    if(NOT EXISTS "${C10_LIBURING_ROOT}/c07-source-commit.txt")
        message(FATAL_ERROR "Provide C10_LIBURING_ROOT with fixed liburing provenance; no installation is attempted")
    endif()
    file(READ "${C10_LIBURING_ROOT}/c07-source-commit.txt" uring_revision)
    string(STRIP "${uring_revision}" uring_revision)
    if(NOT uring_revision STREQUAL "d41bf9220ec39277ff235379e9089d9e0fd6c2a5")
        message(FATAL_ERROR "Unexpected liburing source revision: ${uring_revision}")
    endif()
    find_path(C10_LIBURING_INCLUDE liburing.h PATHS "${C10_LIBURING_ROOT}/include" NO_DEFAULT_PATH REQUIRED)
    find_library(C10_LIBURING_LIBRARY NAMES uring PATHS "${C10_LIBURING_ROOT}/lib" NO_DEFAULT_PATH REQUIRED)
    add_library(c10_liburing UNKNOWN IMPORTED GLOBAL)
    set_target_properties(c10_liburing PROPERTIES IMPORTED_LOCATION "${C10_LIBURING_LIBRARY}"
        INTERFACE_INCLUDE_DIRECTORIES "${C10_LIBURING_INCLUDE}"
        INTERFACE_COMPILE_DEFINITIONS "C07_HAS_LIBURING=1;C10_HAS_LIBURING=1")
endif()
set(C10_STUDY_STUDENT_ROOT "" CACHE PATH "Independent completion directory: root/unit/solution.hpp")
if(NOT DEFINED C10_CXX_STANDARD)
    if(MSVC OR (CMAKE_CXX_COMPILER_ID MATCHES "Clang" AND CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL 18))
        set(C10_CXX_STANDARD 26 CACHE STRING "Requested mode, no silent standard decay")
    else()
        set(C10_CXX_STANDARD 23 CACHE STRING "Requested mode, no silent standard decay")
    endif()
endif()
if(MSVC)
    # Same local mapping as C06; a compiler mode is not a facility probe.
    set(CMAKE_CXX26_STANDARD_COMPILE_OPTION "/std:c++latest")
    set(CMAKE_CXX26_EXTENSION_COMPILE_OPTION "/std:c++latest")
endif()
if(C10_STUDY_ENABLE_ASAN AND C10_STUDY_ENABLE_TSAN)
    message(FATAL_ERROR "ASan and TSan require separate builds")
endif()
if(C10_STUDY_ENABLE_TSAN AND (MSVC OR NOT CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang"))
    message(FATAL_ERROR "No TSan implementation for the requested compiler")
endif()
file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/.cmake/api/v1/query")
file(WRITE "${CMAKE_BINARY_DIR}/.cmake/api/v1/query/codemodel-v2" "")

function(c10_configure_target target)
    cmake_parse_arguments(ARG "NO_ASAN" "" "" ${ARGN})
    set_target_properties(${target} PROPERTIES CXX_STANDARD ${C10_CXX_STANDARD} CXX_STANDARD_REQUIRED ON)
    set_target_properties(${target} PROPERTIES CXX_EXTENSIONS OFF CXX_SCAN_FOR_MODULES OFF)
    target_include_directories(${target} PRIVATE "${C10_EXERCISES}/include"
        "${C10_REPO}/C01_Build_Compile_Link/exercises/include")
    target_link_libraries(${target} PRIVATE Threads::Threads stdexec::stdexec)
    if(MSVC)
        target_compile_options(${target} PRIVATE /utf-8 /EHsc /W4 /permissive- /Zc:__cplusplus)
        if(C10_STUDY_TRACE_INCLUDES)
            target_compile_options(${target} PRIVATE /showIncludes)
        endif()
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
        if(C10_STUDY_TRACE_INCLUDES)
            target_compile_options(${target} PRIVATE -H)
        endif()
    endif()
    if(C10_STUDY_ENABLE_TSAN AND NOT ARG_NO_ASAN)
        target_compile_options(${target} PRIVATE -fsanitize=thread -fno-omit-frame-pointer)
        target_link_options(${target} PRIVATE -fsanitize=thread)
    endif()
    if(C10_STUDY_ENABLE_UBSAN AND NOT ARG_NO_ASAN)
        if(MSVC OR NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
            message(FATAL_ERROR "UBSan is not available with this compiler")
        endif()
        target_compile_options(${target} PRIVATE -fsanitize=undefined -fno-omit-frame-pointer)
        target_link_options(${target} PRIVATE -fsanitize=undefined)
    endif()
    if(C10_STUDY_ENABLE_ASAN AND NOT ARG_NO_ASAN)
        if(MSVC)
            target_compile_options(${target} PRIVATE /fsanitize=address /Zi)
            target_link_options(${target} PRIVATE /INCREMENTAL:NO)
            get_filename_component(compiler_dir "${CMAKE_CXX_COMPILER}" DIRECTORY)
            set(runtime "${compiler_dir}/clang_rt.asan_dynamic-x86_64.dll")
            if(NOT EXISTS "${runtime}")
                message(FATAL_ERROR "Matching x64 ASan runtime missing: ${runtime}")
            endif()
            add_custom_command(TARGET ${target} POST_BUILD COMMAND ${CMAKE_COMMAND} -E
                copy_if_different "${runtime}" "$<TARGET_FILE_DIR:${target}>" VERBATIM)
        elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
            target_compile_options(${target} PRIVATE -fsanitize=address -fno-omit-frame-pointer)
            target_link_options(${target} PRIVATE -fsanitize=address)
        else()
            message(FATAL_ERROR "Unsupported sanitizer compiler")
        endif()
    endif()
endfunction()

function(c10_add_test name)
    cmake_parse_arguments(ARG "ALLOW_SKIP" "TIMEOUT;EXPECT_EXIT;CONTAINS" "COMMAND;LABELS" ${ARGN})
    if(NOT BUILD_TESTING)
        return()
    endif()
    if(NOT ARG_COMMAND)
        set(ARG_COMMAND "$<TARGET_FILE:${name}>")
    endif()
    if(NOT ARG_TIMEOUT)
        set(ARG_TIMEOUT 25)
    endif()
    if(NOT DEFINED ARG_EXPECT_EXIT OR ARG_EXPECT_EXIT STREQUAL "")
        set(ARG_EXPECT_EXIT 0)
    endif()
    set(extra)
    if(ARG_ALLOW_SKIP)
        list(APPEND extra --allow-skip)
    endif()
    if(ARG_CONTAINS)
        list(APPEND extra --contains "${ARG_CONTAINS}")
    endif()
    add_test(NAME ${name} COMMAND "${Python3_EXECUTABLE}" "${C10_REPO}/C07_OS_Memory_System_IO/exercises/tools/run_test.py"
        --name "${name}" --records "${CMAKE_BINARY_DIR}/records/$<CONFIG>"
        --timeout "${ARG_TIMEOUT}" --expect-exit "${ARG_EXPECT_EXIT}" ${extra} -- ${ARG_COMMAND})
    math(EXPR outer_timeout "${ARG_TIMEOUT} + 20")
    set_tests_properties(${name} PROPERTIES TIMEOUT ${outer_timeout} LABELS "${ARG_LABELS}")
    if(ARG_ALLOW_SKIP)
        set_tests_properties(${name} PROPERTIES SKIP_RETURN_CODE 77)
    endif()
endfunction()

function(c10_add_observation name source)
    cmake_parse_arguments(ARG "ALLOW_SKIP;NO_ASAN" "TIMEOUT" "LIBRARIES;ARGS;LABELS" ${ARGN})
    add_executable(${name} ${source})
    set(config_args)
    if(ARG_NO_ASAN)
        list(APPEND config_args NO_ASAN)
    endif()
    c10_configure_target(${name} ${config_args})
    if(ARG_LIBRARIES)
        target_link_libraries(${name} PRIVATE ${ARG_LIBRARIES})
    endif()
    set(test_args)
    if(ARG_ALLOW_SKIP)
        list(APPEND test_args ALLOW_SKIP)
    endif()
    c10_add_test(${name} COMMAND "$<TARGET_FILE:${name}>" ${ARG_ARGS}
        LABELS observation ${ARG_LABELS} TIMEOUT "${ARG_TIMEOUT}" ${test_args})
    c10_record_unit("${name}" "observation" "none" "${source}" "none" "none")
endfunction()

function(c10_add_exercise)
    cmake_parse_arguments(ARG "NO_ASAN;ALLOW_SKIP" "NAME;HEADER;CHECK;BAD_DIAGNOSTIC;STUDENT_EXPECT_EXIT;STUDENT_DIAGNOSTIC" "LIBRARIES;ARGS" ${ARGN})
    foreach(field NAME HEADER CHECK BAD_DIAGNOSTIC)
        if(NOT ARG_${field})
            message(FATAL_ERROR "c10_add_exercise requires ${field}")
        endif()
    endforeach()
    set(variants student)
    if(C10_STUDY_BUILD_REFERENCE)
        list(APPEND variants reference validation_good validation_bad)
    endif()
    foreach(variant IN LISTS variants)
        set(target "${ARG_NAME}_${variant}")
        if(variant MATCHES "^validation_(.*)")
            set(impl "validation/${CMAKE_MATCH_1}")
        else()
            set(impl "src/${variant}")
        endif()
        get_filename_component(impl "${impl}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
        if(variant STREQUAL "student" AND C10_STUDY_STUDENT_ROOT)
            set(impl "${C10_STUDY_STUDENT_ROOT}/${ARG_NAME}")
        endif()
        if(variant STREQUAL "student" AND NOT C10_STUDY_TEST_STUDENTS)
            add_executable(${target} EXCLUDE_FROM_ALL ${ARG_CHECK})
        else()
            add_executable(${target} ${ARG_CHECK})
        endif()
        set(config_args)
        if(ARG_NO_ASAN)
            list(APPEND config_args NO_ASAN)
        endif()
        c10_configure_target(${target} ${config_args})
        target_include_directories(${target} PRIVATE "${impl}"
            "${CMAKE_CURRENT_SOURCE_DIR}/checks")
        if(NOT EXISTS "${impl}/${ARG_HEADER}")
            message(FATAL_ERROR "Missing independent implementation: ${impl}/${ARG_HEADER}")
        endif()
        if(ARG_LIBRARIES)
            target_link_libraries(${target} PRIVATE ${ARG_LIBRARIES})
        endif()
        set(test_args)
        if(ARG_ALLOW_SKIP)
            list(APPEND test_args ALLOW_SKIP)
        endif()
        if(variant STREQUAL "student")
            add_custom_target(${ARG_NAME} DEPENDS ${target})
            set(student_include "${impl}")
            set_property(GLOBAL APPEND PROPERTY C10_STUDENT_TARGETS ${target})
            if(C10_STUDY_TEST_STUDENTS)
                c10_add_test(${target} COMMAND "$<TARGET_FILE:${target}>" ${ARG_ARGS} LABELS student ${test_args})
            endif()
        elseif(variant STREQUAL "validation_bad")
            c10_add_test(${target}_rejected COMMAND "$<TARGET_FILE:${target}>" ${ARG_ARGS}
                EXPECT_EXIT 1 CONTAINS "${ARG_BAD_DIAGNOSTIC}" LABELS negative)
        else()
            c10_add_test(${target} COMMAND "$<TARGET_FILE:${target}>" ${ARG_ARGS} LABELS ${variant} ${test_args})
        endif()
    endforeach()
    c10_record_unit("${ARG_NAME}" "implementation" "${ARG_HEADER}" "${ARG_CHECK}" "${student_include}" "${ARG_BAD_DIAGNOSTIC}")
endfunction()

function(c10_record_unit name kind header check student_include diagnostic)
    set(entry "{}")
    foreach(key name kind header student_include)
        string(REPLACE "\\" "/" value "${${key}}")
        string(JSON entry SET "${entry}" "${key}" "\"${value}\"")
    endforeach()
    string(JSON entry SET "${entry}" source "\"${CMAKE_CURRENT_SOURCE_DIR}\"")
    string(JSON entry SET "${entry}" check_source "\"${CMAKE_CURRENT_SOURCE_DIR}/${check}\"")
    foreach(variant student reference validation_good validation_bad)
        set(key "${variant}_target")
        if(variant STREQUAL "validation_good")
            set(key good_target)
        elseif(variant STREQUAL "validation_bad")
            set(key bad_target)
        endif()
        string(JSON entry SET "${entry}" "${key}" "\"${name}_${variant}\"")
    endforeach()
    string(REPLACE "\"" "\\\"" diagnostic "${diagnostic}")
    string(JSON entry SET "${entry}" bad_diagnostic "\"${diagnostic}\"")
    set(student_exit 2)
    set(student_diagnostic "UNFINISHED")
    if(DEFINED ARG_STUDENT_EXPECT_EXIT AND NOT ARG_STUDENT_EXPECT_EXIT STREQUAL "")
        if(NOT ARG_STUDENT_EXPECT_EXIT MATCHES "^[12]$")
            message(FATAL_ERROR "Initial implementation Student must fail with declared exit 1 or 2")
        endif()
        if(NOT ARG_STUDENT_DIAGNOSTIC)
            message(FATAL_ERROR "A non-default Student expectation requires an exact diagnostic")
        endif()
        set(student_exit "${ARG_STUDENT_EXPECT_EXIT}")
        set(student_diagnostic "${ARG_STUDENT_DIAGNOSTIC}")
    endif()
    string(REPLACE "\"" "\\\"" student_diagnostic "${student_diagnostic}")
    string(JSON entry SET "${entry}" student_expected_exit "${student_exit}")
    string(JSON entry SET "${entry}" student_expected_diagnostic "\"${student_diagnostic}\"")
    get_property(entries GLOBAL PROPERTY C10_UNIT_ENTRIES)
    list(APPEND entries "${entry}")
    set_property(GLOBAL PROPERTY C10_UNIT_ENTRIES "${entries}")
    string(JOIN ",\n" serialized ${entries})
    file(WRITE "${CMAKE_BINARY_DIR}/unit-manifest.json" "{\"units\":[${serialized}]}\n")
endfunction()

function(c10_enable_parallel_scheduler)
    if(TARGET c10_parallel_scheduler)
        return()
    endif()
    add_library(c10_parallel_scheduler STATIC
        "${FETCHCONTENT_SOURCE_DIR_STDEXEC}/src/parallel_scheduler/parallel_scheduler.cpp")
    c10_configure_target(c10_parallel_scheduler)
    target_link_libraries(c10_parallel_scheduler PUBLIC stdexec::stdexec)
    if(WIN32)
        target_compile_definitions(c10_parallel_scheduler PUBLIC STDEXEC_ENABLE_WINDOWS_THREAD_POOL=1)
    endif()
endfunction()
