include_guard(GLOBAL)

function(c04_require_meta_dependency dep prefix_name commit header)
    file(REAL_PATH "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../build/_deps/${prefix_name}" _c04_dep_root)
    set(_marker "${_c04_dep_root}/.learncpp-dependency.cmake")
    if(NOT EXISTS "${_marker}")
        message(FATAL_ERROR "${dep} extension requested but isolated ${prefix_name} is absent; run tools/prepare_meta_libraries.ps1")
    endif()
    include("${_marker}")
    if(NOT LEARNCPP_DEP_COMMIT STREQUAL "${commit}")
        message(FATAL_ERROR "${dep} commit mismatch: ${LEARNCPP_DEP_COMMIT}")
    endif()
    file(REAL_PATH "${LEARNCPP_DEP_SOURCE_DIR}" _c04_dep_source)
    cmake_path(IS_PREFIX _c04_dep_root "${_c04_dep_source}" NORMALIZE _inside_source)
    if(NOT _inside_source)
        message(FATAL_ERROR "${dep} source escaped isolated prefix: ${_c04_dep_source}")
    endif()
    if(NOT EXISTS "${_c04_dep_source}/${header}")
        message(FATAL_ERROR "${dep} header marker missing: ${_c04_dep_source}/${header}")
    endif()
    if(NOT EXISTS "${LEARNCPP_DEP_LICENSE}")
        message(FATAL_ERROR "${dep} license marker missing: ${LEARNCPP_DEP_LICENSE}")
    endif()
    find_program(C04_GIT_EXECUTABLE git REQUIRED)
    execute_process(COMMAND "${C04_GIT_EXECUTABLE}" -C "${_c04_dep_source}" rev-parse HEAD
        RESULT_VARIABLE _head_result OUTPUT_VARIABLE _head OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_VARIABLE _head_error)
    if(NOT _head_result EQUAL 0)
        message(FATAL_ERROR "${dep} git HEAD check failed: ${_head_error}")
    endif()
    if(NOT _head STREQUAL "${commit}")
        message(FATAL_ERROR "${dep} git HEAD mismatch: ${_head}")
    endif()
    execute_process(COMMAND "${C04_GIT_EXECUTABLE}" -C "${_c04_dep_source}" diff-index --quiet HEAD --
        RESULT_VARIABLE _dirty_result ERROR_VARIABLE _dirty_error)
    if(_dirty_result EQUAL 1)
        message(FATAL_ERROR "${dep} checkout has tracked changes: ${_c04_dep_source}")
    elseif(NOT _dirty_result EQUAL 0)
        message(FATAL_ERROR "${dep} tracked dirty check failed: ${_dirty_error}")
    endif()
    set(${dep}_INCLUDE_DIR "${_c04_dep_source}/include" PARENT_SCOPE)
    set(${dep}_SOURCE_DIR "${_c04_dep_source}" PARENT_SCOPE)
endfunction()

function(c04_link_mp11 target)
    if(NOT GENERIC_STUDY_ENABLE_META_LIBS)
        message(FATAL_ERROR "Mp11 target requested while GENERIC_STUDY_ENABLE_META_LIBS=OFF")
    endif()
    c04_require_meta_dependency(C04_MP11 "mp11-boost-1.91.0" "b94b089d4ec83cd397f20958f34edf25bc3e06f4" "include/boost/mp11.hpp")
    target_include_directories(${target} SYSTEM PRIVATE "${C04_MP11_INCLUDE_DIR}")
    target_compile_definitions(${target} PRIVATE C04_MP11_SOURCE_COMMIT="b94b089d4ec83cd397f20958f34edf25bc3e06f4")
endfunction()

function(c04_link_hana target)
    if(NOT GENERIC_STUDY_ENABLE_META_LIBS)
        message(FATAL_ERROR "Hana target requested while GENERIC_STUDY_ENABLE_META_LIBS=OFF")
    endif()
    c04_require_meta_dependency(C04_HANA "hana-boost-1.91.0" "bc49ee25638e59d977edff5737b4e6bf12c1e5ea" "include/boost/hana.hpp")
    target_include_directories(${target} SYSTEM PRIVATE "${C04_HANA_INCLUDE_DIR}")
    target_compile_definitions(${target} PRIVATE C04_HANA_SOURCE_COMMIT="bc49ee25638e59d977edff5737b4e6bf12c1e5ea")
endfunction()
