include_guard(GLOBAL)
include(CTest)
find_package(Python3 3.10 REQUIRED COMPONENTS Interpreter)

option(GENERIC_STUDY_BUILD_REFERENCE "Build independent solutions and checker controls" ON)
option(GENERIC_STUDY_TEST_STUDENTS "Register unfinished student implementations" OFF)
option(GENERIC_STUDY_ENABLE_ASAN "Instrument safe examples" OFF)
option(GENERIC_STUDY_ENABLE_FRONTIER "Probe and run draft-standard examples separately" OFF)
option(GENERIC_STUDY_ENABLE_META_LIBS "Build the pinned Mp11 and Hana teaching units" OFF)

function(c04_configure_target target)
    target_compile_features(${target} PRIVATE cxx_std_23)
    set_target_properties(${target} PROPERTIES CXX_EXTENSIONS OFF CXX_SCAN_FOR_MODULES OFF)
    target_include_directories(${target} PRIVATE
        "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../../C01_Build_Compile_Link/exercises/include")
    if(MSVC)
        target_compile_options(${target} PRIVATE /utf-8 /EHsc /W4 /permissive- /Zc:__cplusplus)
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
    endif()
    if(GENERIC_STUDY_ENABLE_ASAN)
        if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
            target_compile_options(${target} PRIVATE /fsanitize=address /Zi)
            target_link_options(${target} PRIVATE /INCREMENTAL:NO)
            get_filename_component(compiler_dir "${CMAKE_CXX_COMPILER}" DIRECTORY)
            if(CMAKE_SIZEOF_VOID_P EQUAL 8)
                set(arch x86_64)
            else()
                set(arch i386)
            endif()
            set(runtime "${compiler_dir}/clang_rt.asan_dynamic-${arch}.dll")
            if(NOT EXISTS "${runtime}")
                message(FATAL_ERROR "Matching compiler ASan runtime missing: ${runtime}")
            endif()
            add_custom_command(TARGET ${target} POST_BUILD COMMAND ${CMAKE_COMMAND} -E
                copy_if_different "${runtime}" "$<TARGET_FILE_DIR:${target}>" VERBATIM)
        elseif(NOT WIN32 AND CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
            target_compile_options(${target} PRIVATE -fsanitize=address -fno-omit-frame-pointer)
            target_link_options(${target} PRIVATE -fsanitize=address)
        else()
            message(FATAL_ERROR "Use the documented MSVC Windows or Clang/GCC Unix ASan profile")
        endif()
    endif()
endfunction()

# Each rejection has a matching positive source and an isolated build tree.
function(c04_add_compile_case)
    cmake_parse_arguments(ARG "" "NAME;SOURCE;CONTROL;PATTERN;SETUP" "" ${ARGN})
    foreach(field NAME SOURCE CONTROL PATTERN)
        if(NOT ARG_${field})
            message(FATAL_ERROR "c04_add_compile_case requires ${field}")
        endif()
    endforeach()
    get_filename_component(source "${ARG_SOURCE}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    get_filename_component(control "${ARG_CONTROL}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    set(setup_args)
    if(ARG_SETUP)
        get_filename_component(setup "${ARG_SETUP}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
        list(APPEND setup_args --setup "${setup}")
    endif()
    # Keep nested MSVC try-compile paths short and isolate parent builds/configurations.
    string(SHA256 diagnostic_key "${CMAKE_BINARY_DIR}|${ARG_NAME}")
    string(SUBSTRING "${diagnostic_key}" 0 12 diagnostic_key)
    set(diagnostic_build "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../build/_diag/${diagnostic_key}/$<CONFIG>")
    c04_add_test(${ARG_NAME} COMMAND "${Python3_EXECUTABLE}"
        "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tools/compile_case.py"
        --source "${source}" --control "${control}" --pattern "${ARG_PATTERN}"
        --build "${diagnostic_build}"
        --generator "${CMAKE_GENERATOR}" "--platform=${CMAKE_GENERATOR_PLATFORM}"
        --config "$<CONFIG>" --compiler "${CMAKE_CXX_COMPILER}" ${setup_args}
        LABELS diagnostic TIMEOUT 420)
    if(BUILD_TESTING)
        set_tests_properties(${ARG_NAME} PROPERTIES RUN_SERIAL TRUE)
    endif()
endfunction()

function(c04_add_test name)
    cmake_parse_arguments(ARG "" "TIMEOUT" "COMMAND;LABELS" ${ARGN})
    if(NOT BUILD_TESTING)
        return()
    endif()
    if(NOT ARG_COMMAND)
        set(ARG_COMMAND ${name})
    endif()
    if(NOT ARG_TIMEOUT)
        set(ARG_TIMEOUT 30)
    endif()
    add_test(NAME ${name} COMMAND ${ARG_COMMAND})
    set_tests_properties(${name} PROPERTIES TIMEOUT ${ARG_TIMEOUT} LABELS "${ARG_LABELS}")
endfunction()

function(c04_add_observation name source)
    add_executable(${name} ${source})
    c04_configure_target(${name})
    c04_add_test(${name} LABELS observation)
endfunction()

function(c04_add_exercise)
    cmake_parse_arguments(ARG "" "NAME;HEADER;CHECK;BAD_DIAGNOSTIC" "" ${ARGN})
    foreach(field NAME HEADER CHECK BAD_DIAGNOSTIC)
        if(NOT ARG_${field})
            message(FATAL_ERROR "c04_add_exercise requires ${field}")
        endif()
    endforeach()
    set(variants student)
    if(GENERIC_STUDY_BUILD_REFERENCE)
        list(APPEND variants reference validation_good validation_bad)
    endif()
    foreach(variant IN LISTS variants)
        set(target "${ARG_NAME}_${variant}")
        if(variant MATCHES "^validation_(.*)")
            set(impl "validation/${CMAKE_MATCH_1}")
        else()
            set(impl "src/${variant}")
        endif()
        if(variant STREQUAL "student" AND NOT GENERIC_STUDY_TEST_STUDENTS)
            add_executable(${target} EXCLUDE_FROM_ALL ${ARG_CHECK})
        else()
            add_executable(${target} ${ARG_CHECK})
        endif()
        c04_configure_target(${target})
        target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/${impl}"
            "${CMAKE_CURRENT_SOURCE_DIR}/checks")
        if(NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${impl}/${ARG_HEADER}")
            message(FATAL_ERROR "Missing independent implementation: ${impl}/${ARG_HEADER}")
        endif()
        if(variant STREQUAL "student")
            set_property(GLOBAL APPEND PROPERTY C04_STUDENT_TARGETS ${target})
            if(GENERIC_STUDY_TEST_STUDENTS)
                c04_add_test(${target} LABELS student)
            endif()
        elseif(variant STREQUAL "validation_bad")
            c04_add_test(${target}_rejected COMMAND ${CMAKE_COMMAND}
                "-DEXECUTABLE=$<TARGET_FILE:${target}>" "-DEXPECTED_TEXT=${ARG_BAD_DIAGNOSTIC}"
                -P "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/expect_failure.cmake" LABELS negative)
        elseif(variant STREQUAL "reference")
            c04_add_test(${target} LABELS reference)
        else()
            c04_add_test(${target} LABELS validation)
        endif()
    endforeach()
endfunction()
