include_guard(GLOBAL)
option(C12_ENABLE_SQLITE "Build real SQLite laboratories" OFF)
option(C12_ENABLE_POSTGRES "Build real libpq/PostgreSQL laboratories" OFF)
option(C12_ENABLE_FORMATS "Build Boost.JSON and Protobuf comparisons" OFF)
option(C12_ENABLE_SERVICE "Build SQLite/Beast durable admission service" OFF)
option(C12_ENABLE_FRONTIER "Probe the C04 reflection bridge" OFF)
set(C12_SQLITE_ROOT "" CACHE PATH "SQLite 3.53.4 amalgamation directory")
set(C12_POSTGRES_ROOT "" CACHE PATH "PostgreSQL 18.6 private distribution root")
set(C12_BOOST_ROOT "" CACHE PATH "Boost 1.92.0 source directory")
set(C12_PROTOBUF_ROOT "" CACHE PATH "Protobuf 35.1 source checkout")
set(C12_ABSEIL_ROOT "" CACHE PATH "Matching pinned Abseil checkout")
file(READ "${C12_EXERCISES}/../references/dependencies.json" c12_dependency_pins)

function(c12_require_commit directory expected)
  if(NOT IS_DIRECTORY "${directory}")
    message(FATAL_ERROR "Missing explicit dependency directory: ${directory}")
  endif()
  execute_process(COMMAND git -c "safe.directory=${directory}" -C "${directory}" rev-parse HEAD
    OUTPUT_VARIABLE actual OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE status)
  if(NOT status EQUAL 0 OR NOT actual STREQUAL expected)
    message(FATAL_ERROR "Dependency commit differs: ${directory}, expected ${expected}, got ${actual}")
  endif()
  execute_process(COMMAND git -c "safe.directory=${directory}" -C "${directory}" status --porcelain --untracked-files=no
    OUTPUT_VARIABLE dirty OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE status)
  if(NOT status EQUAL 0 OR NOT dirty STREQUAL "")
    message(FATAL_ERROR "Dependency has tracked changes: ${directory}")
  endif()
endfunction()

if(C12_ENABLE_SQLITE)
  if(NOT EXISTS "${C12_SQLITE_ROOT}/sqlite3.c" OR NOT EXISTS "${C12_SQLITE_ROOT}/sqlite3.h")
    message(FATAL_ERROR "C12_ENABLE_SQLITE requires explicitly prepared C12_SQLITE_ROOT")
  endif()
  file(SHA3_256 "${C12_SQLITE_ROOT}/sqlite3.c" actual_hash)
  string(JSON expected_hash GET "${c12_dependency_pins}" sqlite sqlite_c_sha3_256)
  if(NOT actual_hash STREQUAL expected_hash)
    message(FATAL_ERROR "sqlite3.c does not match the official 3.53.4 SHA3")
  endif()
  if(NOT CMAKE_C_COMPILER_LOADED)
    enable_language(C)
  endif()
  add_library(c12_sqlite STATIC "${C12_SQLITE_ROOT}/sqlite3.c")
  target_include_directories(c12_sqlite SYSTEM PUBLIC "${C12_SQLITE_ROOT}")
  target_compile_definitions(c12_sqlite PRIVATE SQLITE_THREADSAFE=1 SQLITE_ENABLE_API_ARMOR=1 SQLITE_DQS=0)
  target_link_libraries(c12_sqlite PRIVATE Threads::Threads ${CMAKE_DL_LIBS})
  if(UNIX)
    target_link_libraries(c12_sqlite PRIVATE m)
  endif()
endif()

if(C12_ENABLE_SERVICE AND NOT C12_ENABLE_SQLITE)
  message(FATAL_ERROR "C12_ENABLE_SERVICE requires C12_ENABLE_SQLITE")
endif()
if(C12_ENABLE_FORMATS OR C12_ENABLE_SERVICE)
  if(NOT EXISTS "${C12_BOOST_ROOT}/boost/version.hpp")
    message(FATAL_ERROR "Formats/service require the explicit C12_BOOST_ROOT")
  endif()
  file(STRINGS "${C12_BOOST_ROOT}/boost/version.hpp" boost_version REGEX "^#define BOOST_VERSION ")
  if(NOT boost_version STREQUAL "#define BOOST_VERSION 109200")
    message(FATAL_ERROR "Expected Boost 1.92.0")
  endif()
  add_library(c12_boost INTERFACE)
  target_include_directories(c12_boost SYSTEM INTERFACE "${C12_BOOST_ROOT}")
  target_compile_definitions(c12_boost INTERFACE BOOST_ALL_NO_LIB)
  if(WIN32)
    target_link_libraries(c12_boost INTERFACE ws2_32)
  endif()
  add_library(c12_json STATIC "${C12_BOOST_ROOT}/libs/json/src/src.cpp")
  target_link_libraries(c12_json PUBLIC c12_boost)
  target_compile_features(c12_json PUBLIC cxx_std_23)
endif()

if(C12_ENABLE_FORMATS)
  c12_require_commit("${C12_PROTOBUF_ROOT}" 35cd01f9fe9afbeea38cc7b979a3b6bfcde82c03)
  c12_require_commit("${C12_ABSEIL_ROOT}" 76bb24329e8bf5f39704eb10d21b9a80befa7c81)
  set(CMAKE_CXX_STANDARD 23)
  set(ABSL_PROPAGATE_CXX_STD ON CACHE BOOL "" FORCE)
  set(ABSL_BUILD_TESTING OFF CACHE BOOL "" FORCE)
  set(protobuf_LOCAL_DEPENDENCIES_ONLY ON CACHE BOOL "" FORCE)
  set(protobuf_FORCE_FETCH_DEPENDENCIES OFF CACHE BOOL "" FORCE)
  set(protobuf_BUILD_TESTS OFF CACHE BOOL "" FORCE)
  set(protobuf_INSTALL OFF CACHE BOOL "" FORCE)
  set(protobuf_WITH_ZLIB OFF CACHE BOOL "" FORCE)
  set(protobuf_MSVC_STATIC_RUNTIME OFF CACHE BOOL "" FORCE)
  add_subdirectory("${C12_ABSEIL_ROOT}" "${CMAKE_BINARY_DIR}/abseil" EXCLUDE_FROM_ALL)
  add_subdirectory("${C12_PROTOBUF_ROOT}" "${CMAKE_BINARY_DIR}/protobuf" EXCLUDE_FROM_ALL)
endif()

if(C12_ENABLE_POSTGRES)
  if(NOT EXISTS "${C12_POSTGRES_ROOT}/include/libpq-fe.h")
    message(FATAL_ERROR "C12_ENABLE_POSTGRES requires C12_POSTGRES_ROOT")
  endif()
  add_library(c12_pq UNKNOWN IMPORTED)
  if(WIN32)
    set(pq_library "${C12_POSTGRES_ROOT}/lib/libpq.lib")
  else()
    find_library(pq_library NAMES pq PATHS "${C12_POSTGRES_ROOT}/lib" NO_DEFAULT_PATH REQUIRED)
  endif()
  if(NOT EXISTS "${pq_library}")
    message(FATAL_ERROR "Private libpq import library not found")
  endif()
  set_target_properties(c12_pq PROPERTIES IMPORTED_LOCATION "${pq_library}"
    INTERFACE_INCLUDE_DIRECTORIES "${C12_POSTGRES_ROOT}/include")
endif()
