include_guard(GLOBAL)
include(CTest)
find_package(Python3 3.11 REQUIRED COMPONENTS Interpreter)
find_package(Threads REQUIRED)
get_filename_component(C12_EXERCISES "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
get_filename_component(C12_REPO "${C12_EXERCISES}/../.." ABSOLUTE)
option(C12_BUILD_REFERENCE "Build reference and independent checker controls" ON)
option(C12_TEST_STUDENTS "Test student implementations (unfinished initially)" OFF)
option(C12_ASAN "Instrument course C++ targets" OFF)
include("${CMAKE_CURRENT_LIST_DIR}/Dependencies.cmake")

function(c12_target target)
  target_compile_features(${target} PRIVATE cxx_std_23)
  set_target_properties(${target} PROPERTIES CXX_EXTENSIONS OFF CXX_SCAN_FOR_MODULES OFF)
  target_include_directories(${target} PRIVATE "${C12_EXERCISES}/include"
    "${C12_REPO}/C01_Build_Compile_Link/exercises/include" "${C12_REPO}/C05_Data_Representation_Standard_Facilities/exercises/include")
  target_link_libraries(${target} PRIVATE Threads::Threads)
  if(WIN32)
    target_compile_definitions(${target} PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX _WIN32_WINNT=0x0A00)
  endif()
  if(MSVC)
    target_compile_options(${target} PRIVATE /utf-8 /W4 /EHsc /permissive- /Zc:__cplusplus /bigobj)
    if(C12_ASAN)
      target_compile_options(${target} PRIVATE /fsanitize=address /Zi)
      target_link_options(${target} PRIVATE /INCREMENTAL:NO)
      get_filename_component(compiler_dir "${CMAKE_CXX_COMPILER}" DIRECTORY)
      add_custom_command(TARGET ${target} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different
        "${compiler_dir}/clang_rt.asan_dynamic-x86_64.dll" "$<TARGET_FILE_DIR:${target}>" VERBATIM)
    endif()
  else()
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
    if(C12_ASAN)
      target_compile_options(${target} PRIVATE -fsanitize=address,undefined -fno-omit-frame-pointer)
      target_link_options(${target} PRIVATE -fsanitize=address,undefined)
    endif()
  endif()
endfunction()

function(c12_test name)
  cmake_parse_arguments(ARG "ALLOW_SKIP" "EXIT;TEXT;TIMEOUT" "COMMAND;LABELS" ${ARGN})
  if(NOT BUILD_TESTING)
    return()
  endif()
  if(NOT DEFINED ARG_EXIT)
    set(ARG_EXIT 0)
  endif()
  if(NOT ARG_TIMEOUT)
    set(ARG_TIMEOUT 30)
  endif()
  if(NOT ARG_COMMAND)
    set(ARG_COMMAND "$<TARGET_FILE:${name}>")
  endif()
  set(extra)
  if(ARG_ALLOW_SKIP)
    list(APPEND extra --allow-skip)
  endif()
  add_test(NAME ${name} COMMAND "${Python3_EXECUTABLE}"
    "${C12_REPO}/C07_OS_Memory_System_IO/exercises/tools/run_test.py"
    --name "${name}" --records "${CMAKE_BINARY_DIR}/records/$<CONFIG>"
    --timeout "${ARG_TIMEOUT}" --expect-exit "${ARG_EXIT}" --contains "${ARG_TEXT}"
    ${extra} -- ${ARG_COMMAND})
  math(EXPR outer "${ARG_TIMEOUT}+20")
  set_tests_properties(${name} PROPERTIES TIMEOUT ${outer} LABELS "${ARG_LABELS}")
  if(ARG_ALLOW_SKIP)
    set_tests_properties(${name} PROPERTIES SKIP_RETURN_CODE 77)
  endif()
endfunction()

function(c12_observation name source)
  add_executable(${name} ${source})
  c12_target(${name})
  c12_test(${name} LABELS observation)
endfunction()

function(c12_exercise name diagnostic)
  set(variants student)
  if(C12_BUILD_REFERENCE)
    list(APPEND variants reference good bad)
  endif()
  foreach(variant IN LISTS variants)
    set(target "${name}_${variant}")
    if(variant STREQUAL "student" AND NOT C12_TEST_STUDENTS)
      add_executable(${target} EXCLUDE_FROM_ALL checks.cpp)
    else()
      add_executable(${target} checks.cpp)
    endif()
    c12_target(${target})
    target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/${variant}")
    if(variant STREQUAL "bad")
      c12_test(${target} EXIT 1 TEXT "${diagnostic}" LABELS checker)
    elseif(NOT variant STREQUAL "student" OR C12_TEST_STUDENTS)
      c12_test(${target} LABELS "${variant}")
    endif()
  endforeach()
endfunction()
