include_guard(GLOBAL)

function(c05_require_format_dependency dep prefix_name commit header)
    file(REAL_PATH "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../build/_deps/${prefix_name}" _c05_dep_root)
    set(_marker "${_c05_dep_root}/.learncpp-dependency.cmake")
    if(NOT EXISTS "${_marker}")
        message(FATAL_ERROR "${dep} extension requested but isolated ${prefix_name} is absent; run tools/prepare_format_libraries.ps1")
    endif()
    include("${_marker}")
    if(NOT LEARNCPP_DEP_COMMIT STREQUAL "${commit}")
        message(FATAL_ERROR "${dep} commit mismatch: ${LEARNCPP_DEP_COMMIT}")
    endif()
    file(REAL_PATH "${LEARNCPP_DEP_SOURCE_DIR}" _c05_dep_source)
    cmake_path(IS_PREFIX _c05_dep_root "${_c05_dep_source}" NORMALIZE _inside_source)
    if(NOT _inside_source)
        message(FATAL_ERROR "${dep} source escaped isolated prefix: ${_c05_dep_source}")
    endif()
    if(NOT EXISTS "${_c05_dep_source}/${header}")
        message(FATAL_ERROR "${dep} header marker missing: ${_c05_dep_source}/${header}")
    endif()
    if(NOT EXISTS "${LEARNCPP_DEP_LICENSE}")
        message(FATAL_ERROR "${dep} license marker missing: ${LEARNCPP_DEP_LICENSE}")
    endif()
    find_program(C05_GIT_EXECUTABLE git REQUIRED)
    execute_process(COMMAND "${C05_GIT_EXECUTABLE}" -C "${_c05_dep_source}" rev-parse HEAD
        RESULT_VARIABLE _head_result OUTPUT_VARIABLE _head OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_VARIABLE _head_error)
    if(NOT _head_result EQUAL 0)
        message(FATAL_ERROR "${dep} git HEAD check failed: ${_head_error}")
    endif()
    if(NOT _head STREQUAL "${commit}")
        message(FATAL_ERROR "${dep} git HEAD mismatch: ${_head}")
    endif()
    execute_process(COMMAND "${C05_GIT_EXECUTABLE}" -C "${_c05_dep_source}" diff-index --quiet HEAD --
        RESULT_VARIABLE _dirty_result ERROR_VARIABLE _dirty_error)
    if(_dirty_result EQUAL 1)
        message(FATAL_ERROR "${dep} checkout has tracked changes: ${_c05_dep_source}")
    elseif(NOT _dirty_result EQUAL 0)
        message(FATAL_ERROR "${dep} tracked dirty check failed: ${_dirty_error}")
    endif()
    set(${dep}_ROOT "${_c05_dep_root}" PARENT_SCOPE)
    set(${dep}_SOURCE_DIR "${_c05_dep_source}" PARENT_SCOPE)
endfunction()

function(c05_assert_pinned_static_target alias target_name source_dir)
    if(NOT TARGET ${alias})
        message(FATAL_ERROR "${alias} target is missing")
    endif()
    get_target_property(_real_target ${alias} ALIASED_TARGET)
    if(NOT _real_target)
        set(_real_target ${alias})
    endif()
    get_target_property(_type ${_real_target} TYPE)
    if(NOT _type STREQUAL "STATIC_LIBRARY")
        message(FATAL_ERROR "${alias} must resolve to a static library, got ${_type}")
    endif()
    get_target_property(_source ${_real_target} SOURCE_DIR)
    if(NOT _source)
        message(FATAL_ERROR "${alias} does not expose SOURCE_DIR")
    endif()
    file(REAL_PATH "${_source}" _source_real)
    file(REAL_PATH "${source_dir}" _expected_source)
    if(NOT "${_source_real}" STREQUAL "${_expected_source}")
        message(FATAL_ERROR "${alias} does not use pinned ${target_name} source: ${_source_real}")
    endif()
endfunction()

function(c05_ensure_fmt)
    if(NOT DATA_STUDY_ENABLE_FORMAT_LIBS)
        message(FATAL_ERROR "fmt target requested while DATA_STUDY_ENABLE_FORMAT_LIBS=OFF")
    endif()
    c05_require_format_dependency(C05_FMT "fmt-12.1.0" "407c905e45ad75fc29bf0f9bb7c5c2fd3475976f" "include/fmt/format.h")
    if(TARGET fmt::fmt)
        c05_assert_pinned_static_target(fmt::fmt fmt "${C05_FMT_SOURCE_DIR}")
        return()
    endif()
    set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
    set(FMT_DOC OFF CACHE BOOL "" FORCE)
    set(FMT_INSTALL OFF CACHE BOOL "" FORCE)
    set(FMT_TEST OFF CACHE BOOL "" FORCE)
    add_subdirectory("${C05_FMT_SOURCE_DIR}" "${CMAKE_BINARY_DIR}/_deps/fmt-12.1.0-build" EXCLUDE_FROM_ALL)
    c05_assert_pinned_static_target(fmt::fmt fmt "${C05_FMT_SOURCE_DIR}")
endfunction()

function(c05_link_fmt target)
    c05_ensure_fmt()
    target_link_libraries(${target} PRIVATE fmt::fmt)
    target_compile_definitions(${target} PRIVATE C05_FMT_SOURCE_COMMIT="407c905e45ad75fc29bf0f9bb7c5c2fd3475976f")
endfunction()

function(c05_ensure_spdlog)
    if(NOT DATA_STUDY_ENABLE_FORMAT_LIBS)
        message(FATAL_ERROR "spdlog target requested while DATA_STUDY_ENABLE_FORMAT_LIBS=OFF")
    endif()
    if(NOT DATA_STUDY_SPDLOG_BACKEND STREQUAL "fmt" AND NOT DATA_STUDY_SPDLOG_BACKEND STREQUAL "std")
        message(FATAL_ERROR "DATA_STUDY_SPDLOG_BACKEND must be fmt or std")
    endif()
    get_property(_selected_backend GLOBAL PROPERTY C05_SPDLOG_BACKEND_SELECTED)
    if(_selected_backend AND NOT "${_selected_backend}" STREQUAL "${DATA_STUDY_SPDLOG_BACKEND}")
        message(FATAL_ERROR "spdlog backend already selected as ${_selected_backend}")
    endif()
    c05_require_format_dependency(C05_SPDLOG "spdlog-1.17.0" "79524ddd08a4ec981b7fea76afd08ee05f83755d" "include/spdlog/spdlog.h")
    if(TARGET spdlog::spdlog)
        c05_assert_pinned_static_target(spdlog::spdlog spdlog "${C05_SPDLOG_SOURCE_DIR}")
        set_property(GLOBAL PROPERTY C05_SPDLOG_BACKEND_SELECTED "${DATA_STUDY_SPDLOG_BACKEND}")
        return()
    endif()
    if(DATA_STUDY_SPDLOG_BACKEND STREQUAL "fmt")
        c05_ensure_fmt()
        set(SPDLOG_FMT_EXTERNAL ON CACHE BOOL "" FORCE)
        set(SPDLOG_FMT_EXTERNAL_HO OFF CACHE BOOL "" FORCE)
        set(SPDLOG_USE_STD_FORMAT OFF CACHE BOOL "" FORCE)
    else()
        set(SPDLOG_FMT_EXTERNAL OFF CACHE BOOL "" FORCE)
        set(SPDLOG_FMT_EXTERNAL_HO OFF CACHE BOOL "" FORCE)
        set(SPDLOG_USE_STD_FORMAT ON CACHE BOOL "" FORCE)
    endif()
    set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
    set(SPDLOG_BUILD_EXAMPLE OFF CACHE BOOL "" FORCE)
    set(SPDLOG_BUILD_EXAMPLE_HO OFF CACHE BOOL "" FORCE)
    set(SPDLOG_BUILD_TESTS OFF CACHE BOOL "" FORCE)
    set(SPDLOG_BUILD_TESTS_HO OFF CACHE BOOL "" FORCE)
    set(SPDLOG_BUILD_BENCH OFF CACHE BOOL "" FORCE)
    set(SPDLOG_INSTALL OFF CACHE BOOL "" FORCE)
    add_subdirectory("${C05_SPDLOG_SOURCE_DIR}" "${CMAKE_BINARY_DIR}/_deps/spdlog-1.17.0-build" EXCLUDE_FROM_ALL)
    c05_assert_pinned_static_target(spdlog::spdlog spdlog "${C05_SPDLOG_SOURCE_DIR}")
    set_property(GLOBAL PROPERTY C05_SPDLOG_BACKEND_SELECTED "${DATA_STUDY_SPDLOG_BACKEND}")
endfunction()

function(c05_link_spdlog target)
    c05_ensure_spdlog()
    target_link_libraries(${target} PRIVATE spdlog::spdlog)
    target_compile_definitions(${target} PRIVATE
        C05_SPDLOG_SOURCE_COMMIT="79524ddd08a4ec981b7fea76afd08ee05f83755d"
        C05_SPDLOG_BACKEND="${DATA_STUDY_SPDLOG_BACKEND}")
endfunction()
