include_guard(GLOBAL)

function(c05_link_icu target)
    if(NOT DATA_STUDY_ENABLE_ICU)
        message(FATAL_ERROR "ICU target requested while DATA_STUDY_ENABLE_ICU=OFF")
    endif()
    file(REAL_PATH "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../build/_deps/icu-77.1" _c05_icu_root)
    if(NOT EXISTS "${_c05_icu_root}/include/unicode/uvernum.h")
        message(FATAL_ERROR "ICU extension requested but isolated ICU 77.1 is absent; run tools/prepare_icu.ps1")
    endif()
    set(ICU_ROOT "${_c05_icu_root}")
    find_package(ICU 77.1 EXACT REQUIRED COMPONENTS uc i18n data)
    set(_inputs ${ICU_INCLUDE_DIRS})
    foreach(_component uc i18n data)
        get_target_property(_includes ICU::${_component} INTERFACE_INCLUDE_DIRECTORIES)
        if(_includes)
            list(APPEND _inputs ${_includes})
        endif()
        foreach(_config RELEASE DEBUG)
            get_target_property(_library ICU::${_component} IMPORTED_LOCATION_${_config})
            if(_library)
                list(APPEND _inputs "${_library}")
            elseif(NOT (_component STREQUAL "data" AND _config STREQUAL "DEBUG"))
                message(FATAL_ERROR "ICU ${_component} ${_config} library missing")
            endif()
        endforeach()
        get_target_property(_fallback ICU::${_component} IMPORTED_LOCATION)
        if(_fallback)
            list(APPEND _inputs "${_fallback}")
        endif()
    endforeach()
    foreach(_input IN LISTS _inputs)
        if(NOT EXISTS "${_input}")
            message(FATAL_ERROR "ICU input missing: ${_input}")
        endif()
        file(REAL_PATH "${_input}" _resolved)
        cmake_path(IS_PREFIX _c05_icu_root "${_resolved}" NORMALIZE _inside)
        if(NOT _inside)
            message(FATAL_ERROR "ICU input escaped isolated prefix: ${_resolved}")
        endif()
    endforeach()
    target_link_libraries(${target} PRIVATE ICU::uc ICU::i18n ICU::data)
    if(WIN32)
        foreach(_file icudt77.dll icuuc77.dll icuuc77d.dll icuin77.dll icuin77d.dll)
            if(NOT EXISTS "${_c05_icu_root}/bin64/${_file}")
                message(FATAL_ERROR "Matching ICU DLL missing: ${_file}")
            endif()
        endforeach()
        add_custom_command(TARGET ${target} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different
            "${_c05_icu_root}/bin64/icudt77.dll"
            "${_c05_icu_root}/bin64/$<IF:$<CONFIG:Debug>,icuuc77d.dll,icuuc77.dll>"
            "${_c05_icu_root}/bin64/$<IF:$<CONFIG:Debug>,icuin77d.dll,icuin77.dll>"
            "$<TARGET_FILE_DIR:${target}>" VERBATIM)
    endif()
endfunction()
