include_guard(GLOBAL)
include(CTest)

option(DATA_STUDY_BUILD_REFERENCE "Build independent solutions and checker controls" ON)
option(DATA_STUDY_TEST_STUDENTS "Register unfinished student implementations" OFF)
option(DATA_STUDY_ENABLE_ASAN "Instrument safe examples" OFF)
option(DATA_STUDY_ENABLE_FRONTIER "Probe and run draft-standard examples separately" OFF)
option(DATA_STUDY_ENABLE_FORMAT_LIBS "Build the pinned fmt and spdlog teaching units" OFF)
set(DATA_STUDY_SPDLOG_BACKEND "fmt" CACHE STRING "Formatting backend for the spdlog experiment: fmt or std")
set_property(CACHE DATA_STUDY_SPDLOG_BACKEND PROPERTY STRINGS fmt std)

function(c05_configure_target target)
    target_compile_features(${target} PRIVATE cxx_std_23)
    set_target_properties(${target} PROPERTIES CXX_EXTENSIONS OFF CXX_SCAN_FOR_MODULES OFF)
    target_include_directories(${target} PRIVATE
        "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../../C01_Build_Compile_Link/exercises/include"
        "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../include")
    if(MSVC)
        target_compile_options(${target} PRIVATE /utf-8 /EHsc /W4 /permissive- /Zc:__cplusplus)
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
    endif()
    if(DATA_STUDY_ENABLE_ASAN)
        if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
            target_compile_options(${target} PRIVATE /fsanitize=address /Zi)
            target_link_options(${target} PRIVATE /INCREMENTAL:NO)
            get_filename_component(compiler_dir "${CMAKE_CXX_COMPILER}" DIRECTORY)
            if(CMAKE_SIZEOF_VOID_P EQUAL 8)
                set(arch x86_64)
            else()
                set(arch i386)
            endif()
            set(runtime "${compiler_dir}/clang_rt.asan_dynamic-${arch}.dll")
            if(NOT EXISTS "${runtime}")
                message(FATAL_ERROR "Matching compiler ASan runtime missing: ${runtime}")
            endif()
            add_custom_command(TARGET ${target} POST_BUILD COMMAND ${CMAKE_COMMAND} -E
                copy_if_different "${runtime}" "$<TARGET_FILE_DIR:${target}>" VERBATIM)
        elseif(NOT WIN32 AND CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
            target_compile_options(${target} PRIVATE -fsanitize=address -fno-omit-frame-pointer)
            target_link_options(${target} PRIVATE -fsanitize=address)
        else()
            message(FATAL_ERROR "Use the documented MSVC Windows or Clang/GCC Unix ASan profile")
        endif()
    endif()
endfunction()

function(c05_add_test name)
    cmake_parse_arguments(ARG "" "TIMEOUT" "COMMAND;LABELS" ${ARGN})
    if(NOT BUILD_TESTING)
        return()
    endif()
    if(NOT ARG_COMMAND)
        set(ARG_COMMAND ${name})
    endif()
    if(NOT ARG_TIMEOUT)
        set(ARG_TIMEOUT 30)
    endif()
    add_test(NAME ${name} COMMAND ${ARG_COMMAND})
    set_tests_properties(${name} PROPERTIES TIMEOUT ${ARG_TIMEOUT} LABELS "${ARG_LABELS}")
endfunction()

function(c05_add_observation name source)
    add_executable(${name} ${source})
    c05_configure_target(${name})
    c05_add_test(${name} LABELS observation)
endfunction()

function(c05_add_exercise)
    cmake_parse_arguments(ARG "" "NAME;HEADER;CHECK;BAD_DIAGNOSTIC" "" ${ARGN})
    foreach(field NAME HEADER CHECK BAD_DIAGNOSTIC)
        if(NOT ARG_${field})
            message(FATAL_ERROR "c05_add_exercise requires ${field}")
        endif()
    endforeach()
    set(variants student)
    if(DATA_STUDY_BUILD_REFERENCE)
        list(APPEND variants reference validation_good validation_bad)
    endif()
    foreach(variant IN LISTS variants)
        set(target "${ARG_NAME}_${variant}")
        if(variant MATCHES "^validation_(.*)")
            set(impl "validation/${CMAKE_MATCH_1}")
        else()
            set(impl "src/${variant}")
        endif()
        if(variant STREQUAL "student" AND NOT DATA_STUDY_TEST_STUDENTS)
            add_executable(${target} EXCLUDE_FROM_ALL ${ARG_CHECK})
        else()
            add_executable(${target} ${ARG_CHECK})
        endif()
        c05_configure_target(${target})
        target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/${impl}"
            "${CMAKE_CURRENT_SOURCE_DIR}/checks")
        if(NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${impl}/${ARG_HEADER}")
            message(FATAL_ERROR "Missing independent implementation: ${impl}/${ARG_HEADER}")
        endif()
        if(variant STREQUAL "student")
            set_property(GLOBAL APPEND PROPERTY C05_STUDENT_TARGETS ${target})
            if(DATA_STUDY_TEST_STUDENTS)
                c05_add_test(${target} LABELS student)
            endif()
        elseif(variant STREQUAL "validation_bad")
            c05_add_test(${target}_rejected COMMAND ${CMAKE_COMMAND}
                "-DEXECUTABLE=$<TARGET_FILE:${target}>" "-DEXPECTED_TEXT=${ARG_BAD_DIAGNOSTIC}"
                -P "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/expect_failure.cmake" LABELS negative)
        elseif(variant STREQUAL "reference")
            c05_add_test(${target} LABELS reference)
        else()
            c05_add_test(${target} LABELS validation)
        endif()
    endforeach()
endfunction()

option(DATA_STUDY_ENABLE_ICU "Build pinned isolated ICU extension" OFF)
