if(NOT DEFINED BINARY_DIR)
    message(FATAL_ERROR "BINARY_DIR is required")
endif()
if(NOT DEFINED BUILD_ROOT)
    set(BUILD_ROOT "${BINARY_DIR}")
endif()
if(NOT DEFINED CONFIG OR CONFIG STREQUAL "")
    set(CONFIG Debug)
endif()

execute_process(
    COMMAND "${CMAKE_COMMAND}" --build "${BUILD_ROOT}" --target C2_archive_library --config "${CONFIG}"
    RESULT_VARIABLE build_result OUTPUT_VARIABLE build_out ERROR_VARIABLE build_err
)
if(NOT build_result EQUAL 0)
    message(FATAL_ERROR "archive build failed:\n${build_out}\n${build_err}")
endif()

file(GLOB_RECURSE candidate_objects "${BINARY_DIR}/*.obj" "${BINARY_DIR}/*.o")
set(used_objects)
foreach(candidate IN LISTS candidate_objects)
    file(TO_CMAKE_PATH "${candidate}" candidate_path)
    if(candidate_path MATCHES "/C2_archive_library[.]dir/"
       AND candidate_path MATCHES "/(used_member[.]cpp[.](obj|o)|used_member[.](obj|o))$")
        list(APPEND used_objects "${candidate}")
    endif()
endforeach()
file(GLOB_RECURSE archives "${BINARY_DIR}/*C2_archive_library*.lib" "${BINARY_DIR}/*libC2_archive_library*.a")

function(_select_config out_var candidates label)
    list(LENGTH candidates count)
    if(count EQUAL 1)
        set(${out_var} "${candidates}" PARENT_SCOPE)
        return()
    endif()
    set(matches)
    foreach(candidate IN LISTS candidates)
        file(TO_CMAKE_PATH "${candidate}" candidate_path)
        if(candidate_path MATCHES "/${CONFIG}/")
            list(APPEND matches "${candidate}")
        endif()
    endforeach()
    list(LENGTH matches match_count)
    if(match_count EQUAL 1)
        set(${out_var} "${matches}" PARENT_SCOPE)
        return()
    endif()
    message(FATAL_ERROR "expected one ${label} for config ${CONFIG}, found ${match_count} matching config out of ${count}: ${candidates}")
endfunction()
_select_config(used_object "${used_objects}" "used_member object")
_select_config(archive_file "${archives}" "archive file")

if(DEFINED DUMPBIN AND EXISTS "${DUMPBIN}")
    execute_process(COMMAND "${DUMPBIN}" /symbols "${used_object}" RESULT_VARIABLE obj_result OUTPUT_VARIABLE obj_out ERROR_VARIABLE obj_err)
    execute_process(COMMAND "${DUMPBIN}" /linkermember:1 "${archive_file}" RESULT_VARIABLE lib_result OUTPUT_VARIABLE lib_out ERROR_VARIABLE lib_err)
    set(def_regex "SECT[0-9A-Fa-f]+[^\n\r]*External[^\n\r]*archive_value")
elseif(DEFINED NM AND EXISTS "${NM}")
    execute_process(COMMAND "${NM}" -C "${used_object}" RESULT_VARIABLE obj_result OUTPUT_VARIABLE obj_out ERROR_VARIABLE obj_err)
    execute_process(COMMAND "${NM}" -C "${archive_file}" RESULT_VARIABLE lib_result OUTPUT_VARIABLE lib_out ERROR_VARIABLE lib_err)
    set(def_regex "(^|\n)[0-9A-Fa-f]+[ \t]+[Tt][ \t]+.*archive_value")
else()
    message(FATAL_ERROR "neither dumpbin nor nm is available")
endif()

if(NOT obj_result EQUAL 0 OR NOT lib_result EQUAL 0)
    message(FATAL_ERROR "symbol tool failed:\n${obj_out}\n${obj_err}\n${lib_out}\n${lib_err}")
endif()
if(NOT obj_out MATCHES "${def_regex}")
    message(FATAL_ERROR "used_member object does not define archive_value:\n${obj_out}\n${obj_err}")
endif()
if(NOT lib_out MATCHES "archive_value")
    message(FATAL_ERROR "archive index does not mention archive_value:\n${lib_out}\n${lib_err}")
endif()

file(MAKE_DIRECTORY "${BINARY_DIR}/evidence")
file(WRITE "${BINARY_DIR}/evidence/symbols.txt" "==== object ====\n${obj_out}\n${obj_err}\n==== archive ====\n${lib_out}\n${lib_err}")
message(STATUS "object and archive symbol evidence contains archive_value")


