if(NOT DEFINED CASE_SOURCE OR NOT DEFINED CASE_BUILD OR NOT DEFINED OBJECT_TARGET OR NOT DEFINED LINK_TARGET OR NOT DEFINED SYMBOL_NAME)
    message(FATAL_ERROR "CASE_SOURCE, CASE_BUILD, OBJECT_TARGET, LINK_TARGET, and SYMBOL_NAME are required")
endif()
if(NOT DEFINED GENERATOR OR GENERATOR STREQUAL "")
    set(generator_args)
else()
    set(generator_args -G "${GENERATOR}")
endif()
if(DEFINED PLATFORM_ARG AND NOT PLATFORM_ARG STREQUAL "")
    list(APPEND generator_args -A "${PLATFORM_ARG}")
endif()
if(DEFINED MAKE_PROGRAM AND NOT MAKE_PROGRAM STREQUAL "")
    set(make_program_arg -DCMAKE_MAKE_PROGRAM=${MAKE_PROGRAM})
else()
    set(make_program_arg)
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${CASE_SOURCE}" -B "${CASE_BUILD}" ${generator_args} ${make_program_arg}
    RESULT_VARIABLE configure_result OUTPUT_VARIABLE configure_out ERROR_VARIABLE configure_err)
if(NOT configure_result EQUAL 0)
    message(FATAL_ERROR "negative case configure failed before object compilation:\n${configure_out}\n${configure_err}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${CASE_BUILD}" --target "${OBJECT_TARGET}" --config Debug
    RESULT_VARIABLE object_result OUTPUT_VARIABLE object_out ERROR_VARIABLE object_err)
if(NOT object_result EQUAL 0)
    message(FATAL_ERROR "negative case object compilation failed before expected link failure:\n${object_out}\n${object_err}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${CASE_BUILD}" --target "${LINK_TARGET}" --config Debug
    RESULT_VARIABLE link_result OUTPUT_VARIABLE link_out ERROR_VARIABLE link_err)
set(combined "${link_out}\n${link_err}")
if(link_result EQUAL 0)
    message(FATAL_ERROR "negative case unexpectedly linked successfully")
endif()
set(msvc_missing FALSE)
if(combined MATCHES "${SYMBOL_NAME}" AND combined MATCHES "(LNK2019|LNK2001|unresolved external symbol)")
    set(msvc_missing TRUE)
endif()
set(gnu_missing FALSE)
if(combined MATCHES "${SYMBOL_NAME}" AND combined MATCHES "undefined reference")
    set(gnu_missing TRUE)
endif()
if(NOT msvc_missing AND NOT gnu_missing)
    message(FATAL_ERROR "negative case failed, but not as an unresolved-symbol link failure for ${SYMBOL_NAME}:\n${combined}")
endif()
message(STATUS "negative case compiled objects, then failed at expected unresolved-symbol link step")
message(STATUS "${combined}")
