include_guard(GLOBAL)
include(CTest)

option(ENGINEERING_STUDY_BUILD_REFERENCE "Build independent reference solutions" ON)
option(ENGINEERING_STUDY_TEST_STUDENTS "Register student implementation checks" OFF)
option(ENGINEERING_STUDY_ENABLE_MODULES "Build named-module lessons" OFF)
option(ENGINEERING_STUDY_ENABLE_IMPORT_STD "Build the separately gated import std lesson" OFF)
option(ENGINEERING_STUDY_ENABLE_UNSAFE_DEMOS "Enable isolated diagnostic fault examples" OFF)

function(engineering_configure_target target)
    target_compile_features(${target} PRIVATE cxx_std_23)
    set_target_properties(${target} PROPERTIES CXX_EXTENSIONS OFF CXX_SCAN_FOR_MODULES OFF)
    target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../include")
    if(MSVC)
        target_compile_options(${target} PRIVATE /utf-8 /EHsc /W4 /Zc:__cplusplus /Zc:preprocessor)
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
    endif()
endfunction()

function(engineering_add_test name)
    cmake_parse_arguments(ARG "" "TIMEOUT" "COMMAND;LABELS" ${ARGN})
    if(NOT BUILD_TESTING)
        return()
    endif()
    if(NOT ARG_COMMAND)
        set(ARG_COMMAND ${name})
    endif()
    if(NOT ARG_TIMEOUT)
        set(ARG_TIMEOUT 30)
    endif()
    add_test(NAME ${name} COMMAND ${ARG_COMMAND})
    set_tests_properties(${name} PROPERTIES TIMEOUT ${ARG_TIMEOUT} LABELS "${ARG_LABELS}")
endfunction()
