include_guard(GLOBAL)

get_filename_component(COROUTINE_STUDY_EXERCISES_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
get_filename_component(COROUTINE_STUDY_COURSE_DIR "${COROUTINE_STUDY_EXERCISES_DIR}/.." ABSOLUTE)
get_filename_component(COROUTINE_STUDY_REPO_ROOT "${COROUTINE_STUDY_COURSE_DIR}/.." ABSOLUTE)

include(CTest)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

if(MSVC)
    add_compile_options(/Zc:__cplusplus /utf-8 /Zc:preprocessor /FS)
endif()

list(APPEND CMAKE_MODULE_PATH "${COROUTINE_STUDY_EXERCISES_DIR}/cmake")

include(AddExercise)
include(ThirdPartySetup)
include("${COROUTINE_STUDY_REPO_ROOT}/cmake/ExerciseIde.cmake")

option(COROUTINE_STUDY_BUILD_REFERENCE "Build reference answer targets when reference sources exist." OFF)
option(COROUTINE_STUDY_FETCH_DEPS "Allow CMake to fetch light third-party dependencies." OFF)
option(COROUTINE_STUDY_ENABLE_STDEXEC "Enable stdexec-based H exercises and capstone bridge code." OFF)
option(COROUTINE_STUDY_ENABLE_ASIO "Enable standalone Asio exercises." OFF)
option(COROUTINE_STUDY_ENABLE_CPPCORO "Enable cppcoro exercises if present." OFF)
option(COROUTINE_STUDY_ENABLE_IO_URING "Enable Linux io_uring exercises." OFF)
set(COROUTINE_STUDY_LIBURING_ROOT "" CACHE PATH "Existing liburing >= 2.15 installation prefix; no system changes.")
option(COROUTINE_STUDY_ENABLE_IOCP "Enable Windows IOCP exercises." OFF)
option(COROUTINE_STUDY_ENABLE_FOLLY "Enable Folly coroutine exercises." OFF)
option(COROUTINE_STUDY_ENABLE_COBALT "Enable Boost.Cobalt coroutine exercises." OFF)
option(COROUTINE_STUDY_ENABLE_UNSAFE_DEMOS "Build demos that intentionally show unsafe coroutine behavior." OFF)
option(COROUTINE_STUDY_ENABLE_STAGE3 "Compatibility umbrella: enable light stage3 deps; prefer per-dependency options." OFF)
option(COROUTINE_STUDY_TEST_STARTERS "Register starter checks that fail until students complete TODOs." OFF)

if(COROUTINE_STUDY_ENABLE_STAGE3)
    message(WARNING "COROUTINE_STUDY_ENABLE_STAGE3 is deprecated; use COROUTINE_STUDY_ENABLE_STDEXEC/ASIO/CPPCORO/IO_URING/IOCP instead.")
    set(COROUTINE_STUDY_ENABLE_STDEXEC ON CACHE BOOL "" FORCE)
    set(COROUTINE_STUDY_ENABLE_ASIO ON CACHE BOOL "" FORCE)
    set(COROUTINE_STUDY_ENABLE_CPPCORO ON CACHE BOOL "" FORCE)
    if(WIN32)
        set(COROUTINE_STUDY_ENABLE_IOCP ON CACHE BOOL "" FORCE)
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        set(COROUTINE_STUDY_ENABLE_IO_URING ON CACHE BOOL "" FORCE)
    endif()
endif()

if(COROUTINE_STUDY_ENABLE_STDEXEC)
    coroutine_study_setup_stdexec(REQUIRED)
endif()
if(COROUTINE_STUDY_ENABLE_ASIO)
    coroutine_study_setup_asio(REQUIRED)
endif()
if(COROUTINE_STUDY_ENABLE_CPPCORO)
    coroutine_study_setup_cppcoro(REQUIRED)
endif()
if(COROUTINE_STUDY_ENABLE_IO_URING)
    coroutine_study_setup_liburing(REQUIRED)
endif()
if(COROUTINE_STUDY_ENABLE_FOLLY)
    coroutine_study_setup_folly(REQUIRED)
endif()
if(COROUTINE_STUDY_ENABLE_COBALT)
    coroutine_study_setup_cobalt(REQUIRED)
endif()

foreach(dependency stdexec cppcoro)
    if(TARGET ${dependency})
        get_target_property(ide_target ${dependency} ALIASED_TARGET)
        if(NOT ide_target)
            set(ide_target ${dependency})
        endif()
        set_property(TARGET ${ide_target} PROPERTY FOLDER "_Course/Dependencies")
    endif()
endforeach()

function(coroutine_study_require_option option feature)
    if(NOT ${option})
        message(FATAL_ERROR "${feature} requires -D${option}=ON when configured directly.")
    endif()
endfunction()
