message("BUILD_DIR=${BUILD_DIR}")
message("TARGET=${TARGET}")
message("CASE=${CASE}")
message("EXPECT=${EXPECT}")
message("OUT_FILE=${OUT_FILE}")
if(DEFINED TARGET)
  message("DEFINED TARGET yes")
else()
  message("DEFINED TARGET no")
endif()
if(NOT DEFINED BUILD_DIR OR NOT DEFINED TARGET OR NOT DEFINED CASE OR NOT DEFINED EXPECT OR NOT DEFINED OUT_FILE)
  message("compound true")
else()
  message("compound false")
endif()
