include_guard(GLOBAL)
option(C11_ENABLE_BOOST "Build Asio/HTTP/WebSocket units from supplied Boost1.92" OFF)
option(C11_ENABLE_TLS "Build TLS tests with supplied OpenSSL3.5.8" OFF)
option(C11_ENABLE_HTTP2 "Build HTTP2 tests with supplied nghttp2 v1.70.0" OFF)
option(C11_ENABLE_QUIC "Build QUIC tests with supplied MsQuic v2.6.1 and its TLS prefix" OFF)
option(C11_ENABLE_GRPC "Build gRPC service from supplied pinned source/submodules" OFF)
option(C11_ENABLE_STDEXEC "Build C10 sender bridge from supplied fixed stdexec" OFF)
set(C11_BOOST_ROOT "" CACHE PATH "Verified Boost1.92 archive root")
set(C11_OPENSSL_ROOT "" CACHE PATH "Private OpenSSL3.5.8 prefix")
set(C11_NGHTTP2_SOURCE "" CACHE PATH "nghttp2 v1.70.0 checkout")
set(C11_MSQUIC_SOURCE "" CACHE PATH "MsQuic v2.6.1 checkout")
set(C11_QUIC_TLS_ROOT "" CACHE PATH "Private prefix built from MsQuic's fixed OpenSSL submodule")
set(C11_GRPC_SOURCE "" CACHE PATH "gRPC v1.84.0 checkout with pinned submodules")
set(C11_STDEXEC_SOURCE "" CACHE PATH "stdexec nvhpc-26.05 checkout")
if(C11_ENABLE_GRPC AND (C11_ENABLE_TLS OR C11_ENABLE_QUIC))
  message(FATAL_ERROR "Build gRPC/BoringSSL in a separate directory from OpenSSL/MsQuic profiles")
endif()
if(C11_ENABLE_QUIC AND NOT WIN32)
  message(FATAL_ERROR "This course's MsQuic build recipe targets Windows; Linux QUIC is not validated")
endif()


function(c11_require_commit directory expected)
  if(NOT IS_DIRECTORY "${directory}")
    message(FATAL_ERROR "Supply the pinned source directory, not an implicit download: ${directory}")
  endif()
  find_package(Git REQUIRED)
  execute_process(COMMAND "${GIT_EXECUTABLE}" -c "safe.directory=${directory}" -C "${directory}" rev-parse HEAD
    OUTPUT_VARIABLE actual OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE status ERROR_QUIET)
  if(NOT status EQUAL 0 OR NOT actual STREQUAL expected)
    message(FATAL_ERROR "Source revision mismatch: expected ${expected}, found ${actual}")
  endif()
endfunction()

if(C11_ENABLE_BOOST)
  if(NOT EXISTS "${C11_BOOST_ROOT}/boost/version.hpp")
    message(FATAL_ERROR "C11_ENABLE_BOOST requires the local C11_BOOST_ROOT")
  endif()
  file(STRINGS "${C11_BOOST_ROOT}/boost/version.hpp" boost_version REGEX "^#define BOOST_VERSION ")
  if(NOT boost_version MATCHES "109200$")
    message(FATAL_ERROR "This course pins Boost1.92.0")
  endif()
  add_library(c11_boost INTERFACE)
  target_include_directories(c11_boost SYSTEM INTERFACE "${C11_BOOST_ROOT}")
  target_compile_definitions(c11_boost INTERFACE BOOST_ALL_NO_LIB)
  add_library(c11_json STATIC "${C11_BOOST_ROOT}/libs/json/src/src.cpp")
  target_link_libraries(c11_json PUBLIC c11_boost)
  target_compile_features(c11_json PUBLIC cxx_std_23)
endif()
if(C11_ENABLE_TLS)
  if(NOT C11_OPENSSL_ROOT)
    message(FATAL_ERROR "C11_ENABLE_TLS requires C11_OPENSSL_ROOT")
  endif()
  set(OPENSSL_ROOT_DIR "${C11_OPENSSL_ROOT}")
  set(OPENSSL_USE_STATIC_LIBS TRUE)
  find_package(OpenSSL 3.5.8 EXACT REQUIRED)
endif()
if(C11_ENABLE_HTTP2)
  enable_language(C)
  c11_require_commit("${C11_NGHTTP2_SOURCE}" 85e300c79fb6dbcfa9c1013215c8710c1c2cd3d2)
  set(ENABLE_LIB_ONLY ON CACHE BOOL "" FORCE)
  set(ENABLE_DOC OFF CACHE BOOL "" FORCE)
  set(ENABLE_FAILMALLOC OFF CACHE BOOL "" FORCE)
  set(BUILD_STATIC_LIBS ON CACHE BOOL "" FORCE)
  set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
  set(c11_saved_testing "${BUILD_TESTING}")
  set(BUILD_TESTING OFF CACHE BOOL "" FORCE)
  add_subdirectory("${C11_NGHTTP2_SOURCE}" "${CMAKE_BINARY_DIR}/nghttp2" EXCLUDE_FROM_ALL)
  set(BUILD_TESTING "${c11_saved_testing}" CACHE BOOL "" FORCE)
endif()
if(C11_ENABLE_GRPC)
  enable_language(C)
  c11_require_commit("${C11_GRPC_SOURCE}" 3252a89f10d8e92997862167ca7d095ecda85973)
  set(gRPC_BUILD_TESTS OFF CACHE BOOL "" FORCE)
  set(gRPC_INSTALL OFF CACHE BOOL "" FORCE)
  set(protobuf_INSTALL OFF CACHE BOOL "" FORCE)
  set(protobuf_BUILD_TESTS OFF CACHE BOOL "" FORCE)
  set(ABSL_BUILD_TESTING OFF CACHE BOOL "" FORCE)
  set(OPENSSL_NO_ASM ON CACHE BOOL "" FORCE)
  foreach(language CSHARP NODE OBJECTIVE_C PHP PYTHON RUBY)
    set(gRPC_BUILD_GRPC_${language}_PLUGIN OFF CACHE BOOL "" FORCE)
  endforeach()
  set(gRPC_SSL_PROVIDER module CACHE STRING "" FORCE)
  set(gRPC_BUILD_GRPC_CPP_PLUGIN ON CACHE BOOL "" FORCE)
  set(c11_saved_testing "${BUILD_TESTING}")
  set(BUILD_TESTING OFF CACHE BOOL "" FORCE)
  add_subdirectory("${C11_GRPC_SOURCE}" "${CMAKE_BINARY_DIR}/grpc" EXCLUDE_FROM_ALL)
  set(BUILD_TESTING "${c11_saved_testing}" CACHE BOOL "" FORCE)
endif()
if(C11_ENABLE_STDEXEC)
  c11_require_commit("${C11_STDEXEC_SOURCE}" 6d7ad689f4d4831c5136e4abe1c601f9a3b64e43)
  add_library(c11_stdexec INTERFACE)
  target_include_directories(c11_stdexec SYSTEM INTERFACE "${C11_STDEXEC_SOURCE}/include")
endif()
if(C11_ENABLE_QUIC)
  enable_language(C)
  c11_require_commit("${C11_MSQUIC_SOURCE}" a01333cf7c2659cce0ff03ef3f21e1ff15bb5b83)
  if(NOT EXISTS "${C11_QUIC_TLS_ROOT}/include/openssl/ssl.h")
    message(FATAL_ERROR "C11_QUIC_TLS_ROOT must hold the separately built pinned MsQuic TLS submodule")
  endif()
  set(QUIC_TLS_LIB openssl CACHE STRING "" FORCE)
  set(QUIC_USE_EXTERNAL_OPENSSL ON CACHE BOOL "" FORCE)
  set(QUIC_OPENSSL_INCLUDE_DIR "${C11_QUIC_TLS_ROOT}/include" CACHE PATH "" FORCE)
  set(QUIC_OPENSSL_LIB_DIR "${C11_QUIC_TLS_ROOT}/lib" CACHE PATH "" FORCE)
  set(QUIC_ENABLE_LOGGING OFF CACHE BOOL "" FORCE)
  set(QUIC_BUILD_TEST OFF CACHE BOOL "" FORCE)
  set(QUIC_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
  set(QUIC_BUILD_SHARED ON CACHE BOOL "" FORCE)
  set(QUIC_STATIC_LINK_CRT OFF CACHE BOOL "" FORCE)
  set(QUIC_STATIC_LINK_PARTIAL_CRT OFF CACHE BOOL "" FORCE)
  add_subdirectory("${C11_MSQUIC_SOURCE}" "${CMAKE_BINARY_DIR}/msquic" EXCLUDE_FROM_ALL)
  if(MSVC)
    # MSVC19.51 C28020 at timestamp transport parameter: (Flags & 0x03000000)
    # >>24 is in [0,3], safely inside QUIC_UINT62. Keep /analyze elsewhere and
    # preserve the original diagnostic in validation records; do not patch upstream.
    set_property(SOURCE "${C11_MSQUIC_SOURCE}/src/core/crypto_tls.c" TARGET_DIRECTORY core
      APPEND PROPERTY COMPILE_OPTIONS /wd28020)
  endif()
endif()
