include_guard(GLOBAL)
include(CTest)
include("${CMAKE_CURRENT_LIST_DIR}/../../../cmake/ExerciseIde.cmake")
find_package(Python3 3.10 REQUIRED COMPONENTS Interpreter)
find_package(Threads REQUIRED)
get_filename_component(C11_EXERCISES "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
get_filename_component(C11_REPO "${C11_EXERCISES}/../.." ABSOLUTE)
if(CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
  set(CMAKE_INSTALL_PREFIX "${CMAKE_BINARY_DIR}/prefix" CACHE PATH "Private course install prefix" FORCE)
endif()
include("${CMAKE_CURRENT_LIST_DIR}/Dependencies.cmake")
option(C11_BUILD_REFERENCE "Build reference implementations and checker controls" ON)
option(C11_TEST_STUDENTS "Register unfinished student implementations (expected to fail)" OFF)
option(C11_ASAN "Instrument course code with address sanitizer" OFF)
option(C11_UBSAN "Instrument course code with undefined behavior sanitizer" OFF)
file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/.cmake/api/v1/query")
file(WRITE "${CMAKE_BINARY_DIR}/.cmake/api/v1/query/codemodel-v2" "")

function(c11_target target)
  target_compile_features(${target} PRIVATE cxx_std_23)
  set_target_properties(${target} PROPERTIES CXX_EXTENSIONS OFF CXX_SCAN_FOR_MODULES OFF)
  target_include_directories(${target} PRIVATE "${C11_EXERCISES}/include" "${C11_REPO}/C01_Build_Compile_Link/exercises/include")
  target_sources(${target} PRIVATE "${C11_REPO}/C01_Build_Compile_Link/exercises/include/check.hpp")
  target_link_libraries(${target} PRIVATE Threads::Threads)
  if(WIN32)
    target_compile_definitions(${target} PRIVATE _WIN32_WINNT=0x0A00 WIN32_LEAN_AND_MEAN NOMINMAX)
    target_link_libraries(${target} PRIVATE ws2_32)
  endif()
  if(MSVC)
    target_compile_options(${target} PRIVATE /utf-8 /EHsc /W4 /permissive- /Zc:__cplusplus /bigobj)
    if(C11_ASAN)
      target_compile_options(${target} PRIVATE /fsanitize=address /Zi)
      target_link_options(${target} PRIVATE /INCREMENTAL:NO)
      get_filename_component(compiler_dir "${CMAKE_CXX_COMPILER}" DIRECTORY)
      add_custom_command(TARGET ${target} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different
        "${compiler_dir}/clang_rt.asan_dynamic-x86_64.dll" "$<TARGET_FILE_DIR:${target}>" VERBATIM)
    endif()
    if(C11_UBSAN)
      message(FATAL_ERROR "MSVC UBSan is not supported; use the Linux UBSan configuration")
    endif()
  else()
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
    if(C11_ASAN)
      target_compile_options(${target} PRIVATE -fsanitize=address -fno-omit-frame-pointer)
      target_link_options(${target} PRIVATE -fsanitize=address)
    endif()
    if(C11_UBSAN)
      target_compile_options(${target} PRIVATE -fsanitize=undefined -fno-sanitize-recover=all)
      target_link_options(${target} PRIVATE -fsanitize=undefined -fno-sanitize-recover=all)
    endif()
  endif()
endfunction()

function(c11_test name target)
  cmake_parse_arguments(ARG "ALLOW_SKIP" "EXIT;DIAGNOSTIC;LABEL;TIMEOUT" "ARGS" ${ARGN})
  if(NOT BUILD_TESTING)
    return()
  endif()
  if(NOT DEFINED ARG_EXIT)
    set(ARG_EXIT 0)
  endif()
  if(NOT ARG_TIMEOUT)
    set(ARG_TIMEOUT 20)
  endif()
  set(extra)
  if(ARG_ALLOW_SKIP)
    list(APPEND extra --allow-skip)
  endif()
  add_test(NAME ${name} COMMAND "${Python3_EXECUTABLE}"
    "${C11_REPO}/C07_OS_Memory_System_IO/exercises/tools/run_test.py"
    --name "${name}" --records "${CMAKE_BINARY_DIR}/records/$<CONFIG>"
    --timeout "${ARG_TIMEOUT}" --expect-exit "${ARG_EXIT}" --contains "${ARG_DIAGNOSTIC}"
    ${extra} -- "$<TARGET_FILE:${target}>" ${ARG_ARGS})
  math(EXPR outer "${ARG_TIMEOUT}+20")
  set_tests_properties(${name} PROPERTIES TIMEOUT ${outer} LABELS "${ARG_LABEL}")
  if(ARG_ALLOW_SKIP)
    set_tests_properties(${name} PROPERTIES SKIP_RETURN_CODE 77)
  endif()
  if(TARGET ${target} AND ARG_ARGS)
    string(JOIN " " debugger_args ${ARG_ARGS})
    set_property(TARGET ${target} PROPERTY VS_DEBUGGER_COMMAND_ARGUMENTS "${debugger_args}")
  endif()
endfunction()

function(c11_exercise name diagnostic)
  cmake_parse_arguments(ARG "" "" "HEADERS" ${ARGN})
  set(variants student)
  if(C11_BUILD_REFERENCE)
    list(APPEND variants reference good bad)
  endif()
  foreach(variant IN LISTS variants)
    set(target "${name}_${variant}")
    if(variant STREQUAL "student" AND NOT C11_TEST_STUDENTS)
      add_executable(${target} EXCLUDE_FROM_ALL checks.cpp)
    else()
      add_executable(${target} checks.cpp)
    endif()
    c11_target(${target})
    target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/${variant}")
    if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${variant}/solution.hpp")
      target_sources(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/${variant}/solution.hpp")
    endif()
    target_sources(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/checks.cpp" ${ARG_HEADERS})
    if(variant STREQUAL "bad")
      c11_test(${target}_rejected ${target} EXIT 1 DIAGNOSTIC "${diagnostic}" LABEL checker)
    elseif(NOT variant STREQUAL "student" OR C11_TEST_STUDENTS)
      c11_test(${target} ${target} LABEL ${variant})
    endif()
  endforeach()
  learncpp_setup_ide("${name}_student")
endfunction()
