include_guard(GLOBAL)

function(c18_require_clang_tooling)
  set(oneValueArgs PREFIX)
  cmake_parse_arguments(ARG "" "${oneValueArgs}" "" ${ARGN})
  if(ARG_PREFIX)
    set(prefix "${ARG_PREFIX}")
  elseif(DEFINED ENV{LLVM18_ROOT})
    set(prefix "$ENV{LLVM18_ROOT}")
  elseif(EXISTS "/usr/lib/llvm-18")
    set(prefix "/usr/lib/llvm-18")
  else()
    message(FATAL_ERROR "C18_ENABLE_CLANG_TOOLING=ON requires LLVM 18.1.3 prefix. Set LLVM18_ROOT or install the fixed LLVM 18.1.3 development files.")
  endif()

  set(clangxx "${prefix}/bin/clang++")
  set(tooling_h "${prefix}/include/clang/Tooling/Tooling.h")
  set(match_h "${prefix}/include/clang/ASTMatchers/ASTMatchFinder.h")
  set(rewrite_h "${prefix}/include/clang/Rewrite/Core/Rewriter.h")
  set(common_h "${prefix}/include/clang/Tooling/CommonOptionsParser.h")
  set(clang_cpp "${prefix}/lib/libclang-cpp.so")
  set(llvm_lib "${prefix}/lib/libLLVM.so")
  if(NOT EXISTS "${llvm_lib}" AND EXISTS "${prefix}/lib/libLLVM-18.so")
    set(llvm_lib "${prefix}/lib/libLLVM-18.so")
  endif()

  if(NOT EXISTS "${clangxx}")
    message(FATAL_ERROR "C18_ENABLE_CLANG_TOOLING=ON requires ${clangxx}.")
  endif()
  execute_process(COMMAND "${clangxx}" --version OUTPUT_VARIABLE version_text ERROR_VARIABLE version_error RESULT_VARIABLE version_rc)
  if(NOT version_rc EQUAL 0 OR NOT version_text MATCHES "18\\.1\\.3")
    message(FATAL_ERROR "C18_ENABLE_CLANG_TOOLING=ON requires clang++ 18.1.3 at ${clangxx}. Output: ${version_text}${version_error}")
  endif()

  foreach(required IN ITEMS "${tooling_h}" "${match_h}" "${rewrite_h}" "${common_h}")
    if(NOT EXISTS "${required}")
      message(FATAL_ERROR "C18_ENABLE_CLANG_TOOLING=ON requires missing Clang development header: ${required}")
    endif()
  endforeach()
  if(NOT EXISTS "${clang_cpp}")
    message(FATAL_ERROR "C18_ENABLE_CLANG_TOOLING=ON requires linkable libclang-cpp symlink: ${clang_cpp}")
  endif()
  if(NOT EXISTS "${llvm_lib}")
    message(FATAL_ERROR "C18_ENABLE_CLANG_TOOLING=ON requires linkable LLVM library under ${prefix}/lib")
  endif()

  set(C18_LLVM18_PREFIX "${prefix}" PARENT_SCOPE)
  set(C18_CLANGXX "${clangxx}" PARENT_SCOPE)
  set(C18_CLANG_CPP_LIB "${clang_cpp}" PARENT_SCOPE)
  set(C18_LLVM_LIB "${llvm_lib}" PARENT_SCOPE)
endfunction()

function(c18_clang_tooling_target target)
  target_include_directories(${target} PRIVATE "${C18_LLVM18_PREFIX}/include" "${C18_EXERCISES}/P2_abi_tool/src")
  target_link_libraries(${target} PRIVATE "${C18_CLANG_CPP_LIB}" "${C18_LLVM_LIB}")
endfunction()
