include_guard(GLOBAL)
include(CTest)
find_package(Python3 3.10 REQUIRED COMPONENTS Interpreter)
find_package(Threads REQUIRED)
get_filename_component(C07_EXERCISES "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
get_filename_component(C07_REPO "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
option(C07_STUDY_BUILD_REFERENCE "Build independent reference and checker controls" ON)
option(C07_STUDY_TEST_STUDENTS "Register incomplete student exercises" OFF)
option(C07_STUDY_ENABLE_ASAN "Instrument safe paths (Linux also UBSan)" OFF)
option(C07_STUDY_ENABLE_IO_URING "Use isolated pinned liburing 2.15 on Linux" OFF)
option(C07_STUDY_TRACE_INCLUDES "Capture actual includes for Student audit" OFF)
set(C07_LIBURING_ROOT "" CACHE PATH "Isolated prefix created by prepare_uring.sh")
if(C07_STUDY_ENABLE_IO_URING)
    if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
        message(FATAL_ERROR "io_uring is Linux-only")
    endif()
    if(C07_LIBURING_ROOT)
        find_path(C07_LIBURING_INCLUDE liburing.h PATHS "${C07_LIBURING_ROOT}/include" NO_DEFAULT_PATH REQUIRED)
        find_library(C07_LIBURING_LIBRARY NAMES uring PATHS "${C07_LIBURING_ROOT}/lib" NO_DEFAULT_PATH REQUIRED)
        file(READ "${C07_LIBURING_ROOT}/c07-source-commit.txt" uring_commit)
        string(STRIP "${uring_commit}" uring_commit)
        if(NOT uring_commit STREQUAL "d41bf9220ec39277ff235379e9089d9e0fd6c2a5")
            message(FATAL_ERROR "Unverified liburing source prefix")
        endif()
        add_library(c07_liburing UNKNOWN IMPORTED)
        set_target_properties(c07_liburing PROPERTIES IMPORTED_LOCATION "${C07_LIBURING_LIBRARY}"
            INTERFACE_INCLUDE_DIRECTORIES "${C07_LIBURING_INCLUDE}"
            INTERFACE_COMPILE_DEFINITIONS C07_HAS_LIBURING=1)
    else()
        find_package(PkgConfig REQUIRED)
        pkg_check_modules(C07_LIBURING REQUIRED IMPORTED_TARGET liburing=2.15)
        target_compile_definitions(PkgConfig::C07_LIBURING INTERFACE C07_HAS_LIBURING=1)
        add_library(c07_liburing ALIAS PkgConfig::C07_LIBURING)
    endif()
endif()

function(c07_configure_target target)
    cmake_parse_arguments(ARG "NO_ASAN" "" "" ${ARGN})
    target_compile_features(${target} PRIVATE cxx_std_23)
    set_target_properties(${target} PROPERTIES CXX_EXTENSIONS OFF CXX_SCAN_FOR_MODULES OFF)
    target_include_directories(${target} PRIVATE "${C07_EXERCISES}/include"
        "${C07_REPO}/C01_Build_Compile_Link/exercises/include")
    target_link_libraries(${target} PRIVATE Threads::Threads)
    if(MSVC)
        target_compile_options(${target} PRIVATE /utf-8 /EHsc /W4 /permissive- /Zc:__cplusplus)
        if(C07_STUDY_TRACE_INCLUDES)
            target_compile_options(${target} PRIVATE /showIncludes)
        endif()
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
        if(C07_STUDY_TRACE_INCLUDES)
            target_compile_options(${target} PRIVATE -H)
        endif()
    endif()
    if(C07_STUDY_ENABLE_ASAN AND NOT ARG_NO_ASAN)
        if(MSVC)
            target_compile_options(${target} PRIVATE /fsanitize=address /Zi)
            target_link_options(${target} PRIVATE /INCREMENTAL:NO)
            get_filename_component(compiler_dir "${CMAKE_CXX_COMPILER}" DIRECTORY)
            set(runtime "${compiler_dir}/clang_rt.asan_dynamic-x86_64.dll")
            if(NOT EXISTS "${runtime}")
                message(FATAL_ERROR "Matching x64 ASan runtime missing: ${runtime}")
            endif()
            add_custom_command(TARGET ${target} POST_BUILD COMMAND ${CMAKE_COMMAND} -E
                copy_if_different "${runtime}" "$<TARGET_FILE_DIR:${target}>" VERBATIM)
        elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
            target_compile_options(${target} PRIVATE -fsanitize=address,undefined -fno-omit-frame-pointer)
            target_link_options(${target} PRIVATE -fsanitize=address,undefined)
        else()
            message(FATAL_ERROR "Unsupported sanitizer compiler")
        endif()
    endif()
endfunction()

function(c07_add_test name)
    cmake_parse_arguments(ARG "ALLOW_SKIP" "TIMEOUT;EXPECT_EXIT;CONTAINS" "COMMAND;LABELS" ${ARGN})
    if(NOT BUILD_TESTING)
        return()
    endif()
    if(NOT ARG_COMMAND)
        set(ARG_COMMAND "$<TARGET_FILE:${name}>")
    endif()
    if(NOT ARG_TIMEOUT)
        set(ARG_TIMEOUT 25)
    endif()
    if(NOT DEFINED ARG_EXPECT_EXIT OR ARG_EXPECT_EXIT STREQUAL "")
        set(ARG_EXPECT_EXIT 0)
    endif()
    set(extra)
    if(ARG_ALLOW_SKIP)
        list(APPEND extra --allow-skip)
    endif()
    if(ARG_CONTAINS)
        list(APPEND extra --contains "${ARG_CONTAINS}")
    endif()
    add_test(NAME ${name} COMMAND "${Python3_EXECUTABLE}" "${C07_EXERCISES}/tools/run_test.py"
        --name "${name}" --records "${CMAKE_BINARY_DIR}/records/$<CONFIG>"
        --timeout "${ARG_TIMEOUT}" --expect-exit "${ARG_EXPECT_EXIT}" ${extra} -- ${ARG_COMMAND})
    math(EXPR outer_timeout "${ARG_TIMEOUT} + 20")
    set_tests_properties(${name} PROPERTIES TIMEOUT ${outer_timeout} LABELS "${ARG_LABELS}")
    if(ARG_ALLOW_SKIP)
        set_tests_properties(${name} PROPERTIES SKIP_RETURN_CODE 77)
    endif()
endfunction()

function(c07_add_observation name source)
    cmake_parse_arguments(ARG "ALLOW_SKIP;NO_ASAN" "TIMEOUT" "LIBRARIES;ARGS;LABELS" ${ARGN})
    add_executable(${name} ${source})
    set(config_args)
    if(ARG_NO_ASAN)
        list(APPEND config_args NO_ASAN)
    endif()
    c07_configure_target(${name} ${config_args})
    if(ARG_LIBRARIES)
        target_link_libraries(${name} PRIVATE ${ARG_LIBRARIES})
    endif()
    set(test_args)
    if(ARG_ALLOW_SKIP)
        list(APPEND test_args ALLOW_SKIP)
    endif()
    c07_add_test(${name} COMMAND "$<TARGET_FILE:${name}>" ${ARG_ARGS}
        LABELS observation ${ARG_LABELS} TIMEOUT "${ARG_TIMEOUT}" ${test_args})
endfunction()

function(c07_add_exercise)
    cmake_parse_arguments(ARG "NO_ASAN;ALLOW_SKIP" "NAME;HEADER;CHECK;BAD_DIAGNOSTIC" "LIBRARIES;ARGS" ${ARGN})
    foreach(field NAME HEADER CHECK BAD_DIAGNOSTIC)
        if(NOT ARG_${field})
            message(FATAL_ERROR "c07_add_exercise requires ${field}")
        endif()
    endforeach()
    set(variants student)
    if(C07_STUDY_BUILD_REFERENCE)
        list(APPEND variants reference validation_good validation_bad)
    endif()
    foreach(variant IN LISTS variants)
        set(target "${ARG_NAME}_${variant}")
        if(variant MATCHES "^validation_(.*)")
            set(impl "validation/${CMAKE_MATCH_1}")
        else()
            set(impl "src/${variant}")
        endif()
        if(variant STREQUAL "student" AND NOT C07_STUDY_TEST_STUDENTS)
            add_executable(${target} EXCLUDE_FROM_ALL ${ARG_CHECK})
        else()
            add_executable(${target} ${ARG_CHECK})
        endif()
        set(config_args)
        if(ARG_NO_ASAN)
            list(APPEND config_args NO_ASAN)
        endif()
        c07_configure_target(${target} ${config_args})
        target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/${impl}"
            "${CMAKE_CURRENT_SOURCE_DIR}/checks")
        if(NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${impl}/${ARG_HEADER}")
            message(FATAL_ERROR "Missing independent implementation: ${impl}/${ARG_HEADER}")
        endif()
        if(ARG_LIBRARIES)
            target_link_libraries(${target} PRIVATE ${ARG_LIBRARIES})
        endif()
        set(test_args)
        if(ARG_ALLOW_SKIP)
            list(APPEND test_args ALLOW_SKIP)
        endif()
        if(variant STREQUAL "student")
            set_property(GLOBAL APPEND PROPERTY C07_STUDENT_TARGETS ${target})
            if(C07_STUDY_TEST_STUDENTS)
                c07_add_test(${target} COMMAND "$<TARGET_FILE:${target}>" ${ARG_ARGS} LABELS student ${test_args})
            endif()
        elseif(variant STREQUAL "validation_bad")
            c07_add_test(${target}_rejected COMMAND "$<TARGET_FILE:${target}>" ${ARG_ARGS}
                EXPECT_EXIT 1 CONTAINS "${ARG_BAD_DIAGNOSTIC}" LABELS negative)
        else()
            c07_add_test(${target} COMMAND "$<TARGET_FILE:${target}>" ${ARG_ARGS} LABELS ${variant} ${test_args})
        endif()
    endforeach()
endfunction()
