include_guard(GLOBAL)
include(CTest)
set_property(GLOBAL PROPERTY USE_FOLDERS ON)
set_property(GLOBAL PROPERTY PREDEFINED_TARGETS_FOLDER "_CMake")
get_property(_engineering_tooling_targets DIRECTORY PROPERTY BUILDSYSTEM_TARGETS)
foreach(_engineering_tooling_target IN LISTS _engineering_tooling_targets)
    get_target_property(_engineering_tooling_folder ${_engineering_tooling_target} FOLDER)
    if(_engineering_tooling_folder STREQUAL "CTestDashboardTargets")
        set_property(TARGET ${_engineering_tooling_target} PROPERTY FOLDER "_CMake/CTest")
    endif()
endforeach()
unset(_engineering_tooling_targets)
unset(_engineering_tooling_target)
unset(_engineering_tooling_folder)

option(ENGINEERING_STUDY_BUILD_REFERENCE "Build independent reference solutions" ON)
option(ENGINEERING_STUDY_TEST_STUDENTS "Register student implementation checks" OFF)
option(ENGINEERING_STUDY_ENABLE_MODULES "Build named-module lessons" OFF)
option(ENGINEERING_STUDY_ENABLE_IMPORT_STD "Build the separately gated import std lesson" OFF)
option(ENGINEERING_STUDY_ENABLE_UNSAFE_DEMOS "Enable isolated diagnostic fault examples" OFF)

function(engineering_configure_target target)
    target_compile_features(${target} PRIVATE cxx_std_23)
    set_target_properties(${target} PROPERTIES CXX_EXTENSIONS OFF CXX_SCAN_FOR_MODULES OFF)
    target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../include")
    target_sources(${target} PRIVATE "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../include/check.hpp")
    if(MSVC)
        target_compile_options(${target} PRIVATE /utf-8 /EHsc /W4 /Zc:__cplusplus /Zc:preprocessor)
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
    endif()
endfunction()

function(engineering_add_test name)
    cmake_parse_arguments(ARG "" "TIMEOUT" "COMMAND;LABELS" ${ARGN})
    if(NOT BUILD_TESTING)
        return()
    endif()
    if(NOT ARG_COMMAND)
        set(ARG_COMMAND ${name})
    endif()
    if(NOT ARG_TIMEOUT)
        set(ARG_TIMEOUT 30)
    endif()
    add_test(NAME ${name} COMMAND ${ARG_COMMAND})
    set_tests_properties(${name} PROPERTIES TIMEOUT ${ARG_TIMEOUT} LABELS "${ARG_LABELS}")
endfunction()

# Call once at the end of a lesson, after declaring its targets.
function(engineering_setup_ide primary)
    cmake_parse_arguments(ARG "" "" "FILES;BROWSE" ${ARGN})
    target_sources(${primary} PRIVATE README.md CMakeLists.txt ${ARG_FILES} ${ARG_BROWSE})
    # These sources are compiled only by independent experiment sub-builds.
    if(ARG_BROWSE)
        set_source_files_properties(${ARG_BROWSE} PROPERTIES HEADER_FILE_ONLY TRUE)
    endif()

    get_property(targets DIRECTORY PROPERTY BUILDSYSTEM_TARGETS)
    foreach(target IN LISTS targets)
        get_target_property(folder ${target} FOLDER)
        if(folder MATCHES "^_CMake(/|$)")
            continue()
        endif()
        get_target_property(type ${target} TYPE)
        if(target STREQUAL primary OR target MATCHES "_student$")
            set(folder "${PROJECT_NAME}")
        elseif(target MATCHES "reference")
            set(folder "${PROJECT_NAME}/Reference")
        elseif(type MATCHES "LIBRARY$" OR target MATCHES "_delegation$")
            set(folder "${PROJECT_NAME}/Support")
        else()
            set(folder "${PROJECT_NAME}/Experiments")
        endif()
        set_property(TARGET ${target} PROPERTY FOLDER "${folder}")
        if(type STREQUAL "EXECUTABLE")
            set_property(TARGET ${target} PROPERTY VS_DEBUGGER_WORKING_DIRECTORY "$<TARGET_FILE_DIR:${target}>")
        endif()
    endforeach()
    get_target_property(primary_type ${primary} TYPE)
    if(primary_type STREQUAL "EXECUTABLE")
        set_property(DIRECTORY PROPERTY VS_STARTUP_PROJECT ${primary})
    endif()

    source_group("Student" REGULAR_EXPRESSION "/src/student/")
    source_group("Reference" REGULAR_EXPRESSION "/(src/)?reference/")
    source_group("Checks" REGULAR_EXPRESSION "/checks/")
    source_group("Support" REGULAR_EXPRESSION "/support/")
    source_group("Headers" REGULAR_EXPRESSION "/include/")
    source_group("Experiments" REGULAR_EXPRESSION "/(observation|negative|consumer|package|debugger|static_analysis|unsafe)/")
    source_group("Docs" REGULAR_EXPRESSION "(README[.]md|CMakeLists[.]txt|[.]cmake([.]in)?|[.]ps1|[.]py|[.]cmd|[.]txt)$")
    source_group(TREE "${CMAKE_CURRENT_SOURCE_DIR}" PREFIX Docs FILES README.md CMakeLists.txt ${ARG_FILES})
    if(ARG_BROWSE)
        source_group(TREE "${CMAKE_CURRENT_SOURCE_DIR}" PREFIX Experiments FILES ${ARG_BROWSE})
    endif()
    source_group("Common" FILES "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../include/check.hpp")
endfunction()
