include_guard(GLOBAL)
function(c13_setup_dependencies)
  if(TARGET c13_stdblas_headers)
    return()
  endif()
  include(FetchContent)
  # Immutable source snapshots; source-only libraries do not configure upstream test projects.
  FetchContent_Declare(gsl_lite URL https://codeload.github.com/gsl-lite/gsl-lite/tar.gz/56dab5ce071c4ca17d3e0dbbda9a94bd5a1cbca1 SOURCE_SUBDIR c13_source_only)
  FetchContent_Declare(xsimd URL https://codeload.github.com/xtensor-stack/xsimd/tar.gz/1f8dd9c8e162968d9b4ff0251c56d431b8777f36 SOURCE_SUBDIR c13_source_only)
  FetchContent_Declare(kokkos_mdspan URL https://codeload.github.com/kokkos/mdspan/tar.gz/8989f70749e28f337e6f7aa210db88659dba6f2f SOURCE_SUBDIR c13_source_only)
  FetchContent_Declare(stdblas URL https://codeload.github.com/kokkos/stdBLAS/tar.gz/146f4743a953e51d7319156f50d932bca7a6507f SOURCE_SUBDIR c13_source_only)
  FetchContent_Declare(mp_units URL https://codeload.github.com/mpusz/mp-units/tar.gz/27d2def9082ce00d7eb4f75695dbead4a748f23f SOURCE_SUBDIR src)
  if(NOT C13_FETCH_DEPS)
    foreach(dep gsl_lite xsimd kokkos_mdspan stdblas mp_units)
      string(TOUPPER "${dep}" upper)
      if(NOT FETCHCONTENT_SOURCE_DIR_${upper} AND NOT EXISTS "${FETCHCONTENT_BASE_DIR}/${dep}-src")
        message(FATAL_ERROR "Missing ${dep}: supply FETCHCONTENT_SOURCE_DIR_${upper} or enable C13_FETCH_DEPS")
      endif()
    endforeach()
    set(FETCHCONTENT_FULLY_DISCONNECTED ON)
  endif()
  FetchContent_MakeAvailable(gsl_lite xsimd kokkos_mdspan stdblas)
  add_library(c13_gsl_lite INTERFACE)
  add_library(gsl-lite::gsl-lite ALIAS c13_gsl_lite)
  target_include_directories(c13_gsl_lite SYSTEM INTERFACE "${gsl_lite_SOURCE_DIR}/include")
  add_library(xsimd INTERFACE)
  target_include_directories(xsimd SYSTEM INTERFACE "${xsimd_SOURCE_DIR}/include")
  set(MP_UNITS_BUILD_CXX_MODULES OFF CACHE BOOL "" FORCE)
  set(MP_UNITS_BUILD_INSTALL OFF CACHE BOOL "" FORCE)
  set(MP_UNITS_API_STD_FORMAT ON CACHE BOOL "" FORCE)
  set(MP_UNITS_API_CONTRACTS GSL-LITE CACHE STRING "" FORCE)
  FetchContent_MakeAvailable(mp_units)

  # Configure the upstream header template; do not enable its optional execution backends.
  foreach(feature ATOMIC_REF BLAS CONCEPTS KOKKOS KOKKOS_DEFAULT TBB)
    set(LINALG_ENABLE_${feature} OFF)
  endforeach()
  set(generated "${stdblas_BINARY_DIR}/include/experimental")
  configure_file("${stdblas_SOURCE_DIR}/include/experimental/__p1673_bits/linalg_config.h.in"
    "${generated}/__p1673_bits/linalg_config.h")
  add_library(c13_stdblas_headers INTERFACE)
  # This stdBLAS snapshot uses mdspan(i,j); enable the reference implementation's compatibility operator.
  target_compile_definitions(c13_stdblas_headers INTERFACE MDSPAN_USE_PAREN_OPERATOR=1)
  target_include_directories(c13_stdblas_headers SYSTEM INTERFACE
    "${generated}" "${stdblas_SOURCE_DIR}/include" "${stdblas_SOURCE_DIR}/include/experimental"
    "${kokkos_mdspan_SOURCE_DIR}/include")
  message(STATUS "[C13] fixed mp-units/gsl-lite/xsimd/stdBLAS/mdspan sources; own consumers only")
endfunction()
