include_guard(GLOBAL)
include(CTest)
find_package(Threads REQUIRED)
get_filename_component(C13_EXERCISES "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
get_filename_component(C13_REPO "${C13_EXERCISES}/../.." ABSOLUTE)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_SCAN_FOR_MODULES OFF)
option(C13_BUILD_REFERENCE "Build independent references and checker controls" ON)
option(C13_TEST_STUDENTS "Run unfinished student implementations (expected to fail)" OFF)
option(C13_ENABLE_THIRD_PARTY "Build pinned third-party numerical examples" OFF)
option(C13_FETCH_DEPS "Allow fetching the pinned source dependencies" OFF)
option(C13_ENABLE_FRONTIER "Probe available native draft-standard examples" OFF)
if(C13_ENABLE_THIRD_PARTY)
  include("${CMAKE_CURRENT_LIST_DIR}/Dependencies.cmake")
  c13_setup_dependencies()
endif()
function(c13_target target)
  target_compile_features(${target} PRIVATE cxx_std_23)
  target_include_directories(${target} PRIVATE "${C13_EXERCISES}/include"
    "${C13_REPO}/C01_Build_Compile_Link/exercises/include" "${C13_REPO}/C08_Concurrency/exercises/include")
  target_link_libraries(${target} PRIVATE Threads::Threads)
  target_compile_definitions(${target} PRIVATE CS_HAS_PARALLEL_ALGORITHMS=1 CS_HAS_STD_SIMD=0)
  if(WIN32)
    target_compile_definitions(${target} PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX)
  endif()
  if(TARGET xsimd)
    target_link_libraries(${target} PRIVATE xsimd)
    target_compile_definitions(${target} PRIVATE CS_HAS_XSIMD=1)
  else()
    target_compile_definitions(${target} PRIVATE CS_HAS_XSIMD=0)
  endif()
  if(MSVC)
    target_compile_options(${target} PRIVATE /utf-8 /EHsc /W4 /permissive- /Zc:__cplusplus /fp:precise)
  else()
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
  endif()
endfunction()
function(c13_test name)
  cmake_parse_arguments(ARG "" "TARGET;TIMEOUT" "ARGS;LABELS" ${ARGN})
  if(NOT ARG_TARGET)
    set(ARG_TARGET ${name})
  endif()
  if(NOT ARG_TIMEOUT)
    set(ARG_TIMEOUT 30)
  endif()
  if(BUILD_TESTING)
    add_test(NAME ${name} COMMAND ${ARG_TARGET} ${ARG_ARGS})
    set_tests_properties(${name} PROPERTIES TIMEOUT ${ARG_TIMEOUT} LABELS "smoke;${ARG_LABELS}")
  endif()
endfunction()
function(c13_observation name source)
  add_executable(${name} ${source})
  c13_target(${name})
  c13_test(${name} LABELS observation)
endfunction()
function(c13_exercise name)
  set(diagnostic "${ARGV1}")
  set(variants student)
  if(C13_BUILD_REFERENCE)
    list(APPEND variants reference good bad)
  endif()
  foreach(variant IN LISTS variants)
    set(target "${name}_${variant}")
    add_executable(${target} checks.cpp)
    c13_target(${target})
    target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/${variant}")
    if(variant STREQUAL "student")
      set_property(GLOBAL APPEND PROPERTY C13_STUDENT_TARGETS ${target})
      if(C13_TEST_STUDENTS)
        c13_test(${target} LABELS student)
      endif()
    elseif(variant STREQUAL "bad")
      if(BUILD_TESTING)
        add_test(NAME ${target}_rejected COMMAND ${CMAKE_COMMAND} "-DPROGRAM=$<TARGET_FILE:${target}>"
          "-DEXPECT_TEXT=${diagnostic}" -P "${C13_EXERCISES}/cmake/ExpectFailure.cmake")
        set_tests_properties(${target}_rejected PROPERTIES TIMEOUT 30 LABELS "smoke;checker")
      endif()
    else()
      c13_test(${target} LABELS ${variant})
    endif()
  endforeach()
endfunction()
