include_guard(GLOBAL)
include(CTest)
find_package(Python3 3.8 REQUIRED COMPONENTS Interpreter)
get_filename_component(C18_EXERCISES "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
get_filename_component(C18_COURSE "${C18_EXERCISES}/.." ABSOLUTE)
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_SCAN_FOR_MODULES OFF)
option(C18_BUILD_REFERENCE "Build answers and independent checker controls" ON)
option(C18_TEST_STUDENTS "Register unfinished student exercises (expected to fail)" OFF)
option(C18_ENABLE_PYTHON "Build native CPython Full C API exercises" OFF)
option(C18_ENABLE_LIMITED_API "Build a CPython 3.8 Limited API extension" OFF)
option(C18_ENABLE_PYBIND11 "Build pinned pybind11 3.0.4 exercises" OFF)
option(C18_ENABLE_LUA "Build pinned Lua 5.4.9 exercises" OFF)
option(C18_ENABLE_CLANG_TOOLING "Build LLVM/Clang 18.1.3 LibTooling exercises" OFF)
option(C18_ENABLE_SANITIZERS "Enable ASan and UBSan on standalone native exercises" OFF)
find_package(Threads REQUIRED)

function(c18_target target)
  target_include_directories(${target} PRIVATE "${C18_EXERCISES}/include" "${C18_EXERCISES}/core")
  if(MSVC)
    target_compile_options(${target} PRIVATE /utf-8 /W4 /permissive- /Zc:__cplusplus /EHsc)
    target_compile_definitions(${target} PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
  else()
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
    if(C18_ENABLE_SANITIZERS)
      target_compile_options(${target} PRIVATE -fsanitize=address,undefined -fno-omit-frame-pointer)
      target_link_options(${target} PRIVATE -fsanitize=address,undefined)
    endif()
  endif()
endfunction()

function(c18_require_native_plugin)
  if(NOT TARGET c18_native_plugin)
    add_library(c18_native_plugin SHARED "${C18_EXERCISES}/L04_plugin_shutdown/fixtures/good_plugin.cpp")
    target_compile_definitions(c18_native_plugin PRIVATE C18_PLUGIN_BUILD)
    c18_target(c18_native_plugin)
    target_link_libraries(c18_native_plugin PRIVATE Threads::Threads)
    set_target_properties(c18_native_plugin PROPERTIES CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN ON)
  endif()
endfunction()

function(c18_add_command_test name)
  cmake_parse_arguments(ARG "ALLOW_SKIP" "EXPECT_FAILURE;TIMEOUT" "COMMAND;LABELS" ${ARGN})
  if(NOT ARG_TIMEOUT)
    set(ARG_TIMEOUT 30)
  endif()
  if(BUILD_TESTING)
    set(extra)
    if(ARG_EXPECT_FAILURE)
      list(APPEND extra --expect-failure "${ARG_EXPECT_FAILURE}")
    endif()
    if(ARG_ALLOW_SKIP)
      list(APPEND extra --allow-skip)
    endif()
    add_test(NAME ${name} COMMAND "${Python3_EXECUTABLE}" "${C18_COURSE}/tools/run_check.py"
      --timeout "${ARG_TIMEOUT}" ${extra} -- ${ARG_COMMAND})
    math(EXPR outer "${ARG_TIMEOUT}+15")
    set_tests_properties(${name} PROPERTIES TIMEOUT ${outer} LABELS "${ARG_LABELS}")
    if(ARG_ALLOW_SKIP)
      set_tests_properties(${name} PROPERTIES SKIP_RETURN_CODE 77)
    endif()
  endif()
endfunction()

function(c18_add_test name target)
  cmake_parse_arguments(ARG "ALLOW_SKIP" "EXPECT_FAILURE;TIMEOUT" "ARGS;LABELS" ${ARGN})
  set(extra)
  if(ARG_ALLOW_SKIP)
    list(APPEND extra ALLOW_SKIP)
  endif()
  c18_add_command_test(${name} COMMAND "$<TARGET_FILE:${target}>" ${ARG_ARGS}
    EXPECT_FAILURE "${ARG_EXPECT_FAILURE}" TIMEOUT "${ARG_TIMEOUT}" LABELS ${ARG_LABELS} ${extra})
endfunction()

function(c18_exercise name)
  cmake_parse_arguments(ARG "" "EXPECT" "" ${ARGN})
  if(NOT ARG_EXPECT)
    message(FATAL_ERROR "c18_exercise requires EXPECT with the intended bad implementation diagnostic")
  endif()
  set(variants student)
  if(C18_BUILD_REFERENCE)
    list(APPEND variants reference good bad)
  endif()
  foreach(variant IN LISTS variants)
    if(variant STREQUAL "good" OR variant STREQUAL "bad")
      set(implementation "validation/${variant}")
    else()
      set(implementation "${variant}")
    endif()
    set(target "${name}_${variant}")
    add_executable(${target} checks.cpp)
    c18_target(${target})
    target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/${implementation}")
    target_link_libraries(${target} PRIVATE Threads::Threads ${CMAKE_DL_LIBS})
    if(variant STREQUAL "student")
      if(C18_TEST_STUDENTS)
        c18_add_test(${target} ${target} LABELS student)
      endif()
    elseif(variant STREQUAL "bad")
      c18_add_test(${target}_rejected ${target} EXPECT_FAILURE "${ARG_EXPECT}" LABELS checker)
    else()
      c18_add_test(${target} ${target} LABELS "${variant}")
    endif()
  endforeach()
endfunction()
