include_guard(GLOBAL)
if(TARGET xsimd)
    return()
endif()
include("${CMAKE_CURRENT_LIST_DIR}/DependencyRevision.cmake")
set(CONCURRENCY_STUDY_XSIMD_REVISION "1f8dd9c8e162968d9b4ff0251c56d431b8777f36" CACHE INTERNAL "xsimd 13.2.0 peeled commit" FORCE)
set(CONCURRENCY_STUDY_XSIMD_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/../third_party/xsimd" CACHE PATH "Existing xsimd 13.2.0 source checkout")
if(EXISTS "${CONCURRENCY_STUDY_XSIMD_SOURCE_DIR}/include/xsimd/xsimd.hpp")
    cs_verify_checkout("${CONCURRENCY_STUDY_XSIMD_SOURCE_DIR}" "${CONCURRENCY_STUDY_XSIMD_REVISION}" xsimd)
    set(_cs_xsimd_include "${CONCURRENCY_STUDY_XSIMD_SOURCE_DIR}/include")
else()
    find_package(xsimd 13.2.0 EXACT QUIET CONFIG)
    if(TARGET xsimd)
        set(CONCURRENCY_STUDY_XSIMD_REVISION "installed package 13.2.0; source commit not verified" CACHE INTERNAL "Dependency provenance" FORCE)
        return()
    endif()
    if(NOT CONCURRENCY_STUDY_FETCH_DEPS)
        message(FATAL_ERROR "xsimd 13.2.0 is not available. Set CONCURRENCY_STUDY_XSIMD_SOURCE_DIR or explicitly enable CONCURRENCY_STUDY_FETCH_DEPS.")
    endif()
    include(FetchContent)
    FetchContent_Declare(xsimd
        GIT_REPOSITORY https://github.com/xtensor-stack/xsimd.git
        GIT_TAG 1f8dd9c8e162968d9b4ff0251c56d431b8777f36
        SOURCE_SUBDIR _cs_headers_only)
    FetchContent_MakeAvailable(xsimd)
    cs_verify_checkout("${xsimd_SOURCE_DIR}" "1f8dd9c8e162968d9b4ff0251c56d431b8777f36" xsimd)
    set(_cs_xsimd_include "${xsimd_SOURCE_DIR}/include")
endif()
add_library(xsimd INTERFACE)
target_include_directories(xsimd INTERFACE "${_cs_xsimd_include}")
message(STATUS "[study] xsimd headers: ${_cs_xsimd_include}; expected source version: 13.2.0")
