include_guard(GLOBAL)

include(CheckCXXCompilerFlag)

function(coroutine_study_enable_cxx26_preview target)
    if(MSVC)
        target_compile_options(${target} PRIVATE /std:c++latest)
        return()
    endif()

    check_cxx_compiler_flag("-std=c++2c" COROUTINE_STUDY_HAS_CXX2C_FLAG)
    if(COROUTINE_STUDY_HAS_CXX2C_FLAG)
        target_compile_options(${target} PRIVATE -std=c++2c)
    else()
        message(FATAL_ERROR "${target} requires a compiler with a C++26 preview flag.")
    endif()
endfunction()

function(coroutine_study_add_exercise name)
    cmake_parse_arguments(ARG "" "STANDARD" "SOURCES;REFERENCE_SOURCES;LIBRARIES" ${ARGN})
    if(NOT ARG_SOURCES)
        set(ARG_SOURCES main.cpp)
    endif()
    if(NOT ARG_STANDARD)
        set(ARG_STANDARD 23)
    endif()

    add_executable(${name} ${ARG_SOURCES})
    target_compile_features(${name} PRIVATE cxx_std_${ARG_STANDARD})
    if(NOT COROUTINE_STUDY_EXERCISES_DIR)
        message(FATAL_ERROR "COROUTINE_STUDY_EXERCISES_DIR must point to Coroutine_Study/exercises")
    endif()
    target_include_directories(${name} PRIVATE "${COROUTINE_STUDY_EXERCISES_DIR}/include")
    if(ARG_LIBRARIES)
        target_link_libraries(${name} PRIVATE ${ARG_LIBRARIES})
    endif()
    if(COROUTINE_STUDY_BUILD_REFERENCE AND ARG_REFERENCE_SOURCES)
        add_executable(${name}_reference ${ARG_REFERENCE_SOURCES})
        target_compile_features(${name}_reference PRIVATE cxx_std_${ARG_STANDARD})
        target_include_directories(${name}_reference PRIVATE "${COROUTINE_STUDY_EXERCISES_DIR}/include")
        if(ARG_LIBRARIES)
            target_link_libraries(${name}_reference PRIVATE ${ARG_LIBRARIES})
        endif()
        if(BUILD_TESTING)
            add_test(NAME ${name}_reference COMMAND ${name}_reference)
        endif()
    endif()
endfunction()
