include_guard(GLOBAL)
set(CONCURRENCY_STUDY_SANITIZER "none" CACHE STRING "Instrumentation: none, address, thread")
set_property(CACHE CONCURRENCY_STUDY_SANITIZER PROPERTY STRINGS none address thread)
if(NOT CONCURRENCY_STUDY_SANITIZER MATCHES "^(none|address|thread)$")
    message(FATAL_ERROR "CONCURRENCY_STUDY_SANITIZER must be none, address, or thread")
endif()

function(cs_enable_sanitizer target)
    if(CONCURRENCY_STUDY_SANITIZER STREQUAL "none")
        return()
    endif()
    if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC" AND CONCURRENCY_STUDY_SANITIZER STREQUAL "address")
        # The Windows ASan preset uses RelWithDebInfo, without Debug's /RTC1.
        target_compile_options(${target} PRIVATE /fsanitize=address /Zi)
        target_link_options(${target} PRIVATE /INCREMENTAL:NO)
        get_target_property(_cs_type ${target} TYPE)
        if(_cs_type STREQUAL "EXECUTABLE")
            get_filename_component(_cs_compiler_dir "${CMAKE_CXX_COMPILER}" DIRECTORY)
            if(CMAKE_SIZEOF_VOID_P EQUAL 8)
                set(_cs_arch x86_64)
            else()
                set(_cs_arch i386)
            endif()
            set(_cs_runtime "${_cs_compiler_dir}/clang_rt.asan_dynamic-${_cs_arch}.dll")
            if(NOT EXISTS "${_cs_runtime}")
                message(FATAL_ERROR "Matching compiler ASan runtime missing: ${_cs_runtime}")
            endif()
            add_custom_command(TARGET ${target} POST_BUILD COMMAND ${CMAKE_COMMAND} -E
                copy_if_different "${_cs_runtime}" "$<TARGET_FILE_DIR:${target}>" VERBATIM)
        endif()
    elseif(NOT WIN32 AND CMAKE_CXX_COMPILER_ID MATCHES "^(Clang|GNU)$")
        if(CONCURRENCY_STUDY_SANITIZER STREQUAL "address")
            set(_cs_instrumentation address,undefined)
        else()
            set(_cs_instrumentation thread)
        endif()
        target_compile_options(${target} PRIVATE -fsanitize=${_cs_instrumentation} -fno-omit-frame-pointer -g)
        target_link_options(${target} PRIVATE -fsanitize=${_cs_instrumentation})
    else()
        message(FATAL_ERROR "Use MSVC Windows ASan or Clang/GCC Linux ASan/UBSan or TSan")
    endif()
endfunction()
