include_guard(GLOBAL)

option(CONCURRENCY_STUDY_ENABLE_SPDLOG "Build the pinned spdlog async logging unit" OFF)
set(CONCURRENCY_STUDY_FMT_SOURCE_DIR
    "${CONCURRENCY_STUDY_EXERCISES_DIR}/../../C05_Data_Representation_Standard_Facilities/exercises/build/_deps/fmt-12.1.0/source"
    CACHE PATH "Explicit fmt 12.1.0 source directory")
set(CONCURRENCY_STUDY_SPDLOG_SOURCE_DIR
    "${CONCURRENCY_STUDY_EXERCISES_DIR}/../../C05_Data_Representation_Standard_Facilities/exercises/build/_deps/spdlog-1.17.0/source"
    CACHE PATH "Explicit spdlog 1.17.0 source directory")

function(cs_require_clean_git_source dep source_dir commit header)
    file(REAL_PATH "${source_dir}" _source)
    if(NOT EXISTS "${_source}/${header}")
        message(FATAL_ERROR "${dep} header marker missing: ${_source}/${header}")
    endif()
    find_program(CS_GIT_EXECUTABLE git REQUIRED)
    execute_process(COMMAND "${CS_GIT_EXECUTABLE}" -C "${_source}" rev-parse HEAD
        RESULT_VARIABLE _head_result OUTPUT_VARIABLE _head OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_VARIABLE _head_error)
    if(NOT _head_result EQUAL 0)
        message(FATAL_ERROR "${dep} git HEAD check failed: ${_head_error}")
    endif()
    if(NOT _head STREQUAL "${commit}")
        message(FATAL_ERROR "${dep} git HEAD mismatch: ${_head}")
    endif()
    execute_process(COMMAND "${CS_GIT_EXECUTABLE}" -C "${_source}" diff-index --quiet HEAD --
        RESULT_VARIABLE _dirty_result ERROR_VARIABLE _dirty_error)
    if(_dirty_result EQUAL 1)
        message(FATAL_ERROR "${dep} checkout has tracked changes: ${_source}")
    elseif(NOT _dirty_result EQUAL 0)
        message(FATAL_ERROR "${dep} tracked dirty check failed: ${_dirty_error}")
    endif()
    set(${dep}_SOURCE_DIR "${_source}" PARENT_SCOPE)
endfunction()

function(cs_assert_static_source alias source_dir)
    if(NOT TARGET ${alias})
        message(FATAL_ERROR "${alias} target is missing")
    endif()
    get_target_property(_real ${alias} ALIASED_TARGET)
    if(NOT _real)
        set(_real ${alias})
    endif()
    get_target_property(_type ${_real} TYPE)
    if(NOT _type STREQUAL "STATIC_LIBRARY")
        message(FATAL_ERROR "${alias} must be a static library, got ${_type}")
    endif()
    get_target_property(_source ${_real} SOURCE_DIR)
    file(REAL_PATH "${_source}" _actual)
    file(REAL_PATH "${source_dir}" _expected)
    if(NOT "${_actual}" STREQUAL "${_expected}")
        message(FATAL_ERROR "${alias} source mismatch: ${_actual}")
    endif()
endfunction()

function(cs_enable_dependency_sanitizer alias)
    get_target_property(_real ${alias} ALIASED_TARGET)
    if(NOT _real)
        set(_real ${alias})
    endif()
    get_property(_done TARGET ${_real} PROPERTY CS_SANITIZER_APPLIED)
    if(NOT _done)
        cs_enable_sanitizer(${_real})
        set_property(TARGET ${_real} PROPERTY CS_SANITIZER_APPLIED TRUE)
    endif()
endfunction()

function(cs_ensure_spdlog)
    cs_require_clean_git_source(CS_FMT "${CONCURRENCY_STUDY_FMT_SOURCE_DIR}"
        "407c905e45ad75fc29bf0f9bb7c5c2fd3475976f" "include/fmt/format.h")
    cs_require_clean_git_source(CS_SPDLOG "${CONCURRENCY_STUDY_SPDLOG_SOURCE_DIR}"
        "79524ddd08a4ec981b7fea76afd08ee05f83755d" "include/spdlog/spdlog.h")
    if(NOT TARGET fmt::fmt)
        set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
        set(FMT_DOC OFF CACHE BOOL "" FORCE)
        set(FMT_INSTALL OFF CACHE BOOL "" FORCE)
        set(FMT_TEST OFF CACHE BOOL "" FORCE)
        add_subdirectory("${CS_FMT_SOURCE_DIR}" "${CMAKE_BINARY_DIR}/_deps/fmt-12.1.0-build" EXCLUDE_FROM_ALL)
    endif()
    cs_assert_static_source(fmt::fmt "${CS_FMT_SOURCE_DIR}")
    cs_enable_dependency_sanitizer(fmt::fmt)
    if(NOT TARGET spdlog::spdlog)
        set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
        set(SPDLOG_FMT_EXTERNAL ON CACHE BOOL "" FORCE)
        set(SPDLOG_FMT_EXTERNAL_HO OFF CACHE BOOL "" FORCE)
        set(SPDLOG_USE_STD_FORMAT OFF CACHE BOOL "" FORCE)
        set(SPDLOG_BUILD_EXAMPLE OFF CACHE BOOL "" FORCE)
        set(SPDLOG_BUILD_EXAMPLE_HO OFF CACHE BOOL "" FORCE)
        set(SPDLOG_BUILD_TESTS OFF CACHE BOOL "" FORCE)
        set(SPDLOG_BUILD_TESTS_HO OFF CACHE BOOL "" FORCE)
        set(SPDLOG_BUILD_BENCH OFF CACHE BOOL "" FORCE)
        set(SPDLOG_INSTALL OFF CACHE BOOL "" FORCE)
        add_subdirectory("${CS_SPDLOG_SOURCE_DIR}" "${CMAKE_BINARY_DIR}/_deps/spdlog-1.17.0-build" EXCLUDE_FROM_ALL)
    endif()
    cs_assert_static_source(spdlog::spdlog "${CS_SPDLOG_SOURCE_DIR}")
    cs_enable_dependency_sanitizer(spdlog::spdlog)
    set(CS_FMT_SOURCE_DIR "${CS_FMT_SOURCE_DIR}" PARENT_SCOPE)
    set(CS_SPDLOG_SOURCE_DIR "${CS_SPDLOG_SOURCE_DIR}" PARENT_SCOPE)
endfunction()

function(cs_link_spdlog target)
    cs_ensure_spdlog()
    target_link_libraries(${target} PRIVATE spdlog::spdlog)
    target_compile_definitions(${target} PRIVATE
        CS_FMT_SOURCE_COMMIT="407c905e45ad75fc29bf0f9bb7c5c2fd3475976f"
        CS_SPDLOG_SOURCE_COMMIT="79524ddd08a4ec981b7fea76afd08ee05f83755d")
endfunction()
