include_guard(GLOBAL)
include(CTest)

option(CORE_STUDY_BUILD_REFERENCE "Build independent reference implementations" ON)
option(CORE_STUDY_TEST_STUDENTS "Register student implementation checks" OFF)
option(CORE_STUDY_ENABLE_UNSAFE_DEMOS "Build isolated intentional diagnostic faults" OFF)
option(CORE_STUDY_ENABLE_FRONTIER "Enable separately probed draft-standard experiments" OFF)
option(CORE_STUDY_ENABLE_ASAN "Instrument safe examples with AddressSanitizer" OFF)

function(core_configure_target target)
    target_compile_features(${target} PRIVATE cxx_std_23)
    set_target_properties(${target} PROPERTIES CXX_EXTENSIONS OFF CXX_SCAN_FOR_MODULES OFF)
    target_include_directories(${target} BEFORE PRIVATE
        "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../../C01_Build_Compile_Link/exercises/include")
    if(MSVC)
        target_compile_options(${target} PRIVATE /utf-8 /EHsc /W4 /permissive- /Zc:__cplusplus)
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
    endif()
    if(CORE_STUDY_ENABLE_ASAN)
        if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
            if(CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
                # Match clang-cl /MD ASan driver linking, including the SEH thunk.
                set_target_properties(${target} PROPERTIES MSVC_RUNTIME_LIBRARY MultiThreadedDLL)
                target_compile_options(${target} PRIVATE /fsanitize=address -fno-omit-frame-pointer)
                target_link_options(${target} PRIVATE /INCREMENTAL:NO)
            else()
                target_compile_options(${target} PRIVATE -fsanitize=address -fno-omit-frame-pointer)
                target_link_options(${target} PRIVATE -fsanitize=address)
            endif()
        elseif(MSVC)
            target_compile_options(${target} PRIVATE /fsanitize=address /Zi)
            target_link_options(${target} PRIVATE /INCREMENTAL:NO)
        else()
            message(FATAL_ERROR "This ASan profile requires the documented Clang or MSVC toolchain")
        endif()
        if(WIN32)
            get_target_property(_core_kind ${target} TYPE)
            if(_core_kind MATCHES "^(EXECUTABLE|SHARED_LIBRARY|MODULE_LIBRARY)$")
                if(CMAKE_SIZEOF_VOID_P EQUAL 8)
                    set(_core_arch x86_64)
                else()
                    set(_core_arch i386)
                endif()
                if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
                    get_filename_component(_core_compiler_dir "${CMAKE_CXX_COMPILER}" DIRECTORY)
                    set(_core_runtime "${_core_compiler_dir}/clang_rt.asan_dynamic-${_core_arch}.dll")
                else()
                    execute_process(COMMAND "${CMAKE_CXX_COMPILER}" --print-resource-dir
                        RESULT_VARIABLE _core_resource_result OUTPUT_VARIABLE _core_resource_dir
                        OUTPUT_STRIP_TRAILING_WHITESPACE TIMEOUT 10)
                    if(NOT _core_resource_result EQUAL 0)
                        message(FATAL_ERROR "Cannot query this Clang compiler's resource directory")
                    endif()
                    find_file(_core_runtime NAMES "clang_rt.asan_dynamic-${_core_arch}.dll"
                        PATHS "${_core_resource_dir}/lib/windows"
                              "${_core_resource_dir}/lib/${_core_arch}-pc-windows-msvc"
                        NO_DEFAULT_PATH NO_CACHE)
                endif()
                if(NOT EXISTS "${_core_runtime}")
                    message(FATAL_ERROR "Matching ASan runtime for ${CMAKE_CXX_COMPILER} is missing; do not substitute a same-named DLL from another compiler")
                endif()
                if(CMAKE_CXX_COMPILER_ID MATCHES "Clang" AND
                   CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
                    get_filename_component(_core_runtime_dir "${_core_runtime}" DIRECTORY)
                    set(_core_import "${_core_runtime_dir}/clang_rt.asan_dynamic-${_core_arch}.lib")
                    set(_core_thunk "${_core_runtime_dir}/clang_rt.asan_dynamic_runtime_thunk-${_core_arch}.lib")
                    if(NOT EXISTS "${_core_import}" OR NOT EXISTS "${_core_thunk}")
                        message(FATAL_ERROR "Matching clang-cl ASan import/thunk libraries are missing")
                    endif()
                    target_link_libraries(${target} PRIVATE "${_core_import}")
                    target_link_options(${target} PRIVATE "/WHOLEARCHIVE:${_core_thunk}")
                    if(CMAKE_SIZEOF_VOID_P EQUAL 8)
                        target_link_options(${target} PRIVATE /INCLUDE:__asan_seh_interceptor)
                    else()
                        target_link_options(${target} PRIVATE /INCLUDE:___asan_seh_interceptor)
                    endif()
                endif()
                add_custom_command(TARGET ${target} POST_BUILD
                    COMMAND "${CMAKE_COMMAND}" -E copy_if_different
                        "${_core_runtime}" "$<TARGET_FILE_DIR:${target}>"
                    VERBATIM)
            endif()
        endif()
    endif()
endfunction()

function(core_add_test name)
    cmake_parse_arguments(ARG "" "TIMEOUT" "COMMAND;LABELS" ${ARGN})
    if(NOT BUILD_TESTING)
        return()
    endif()
    if(NOT ARG_COMMAND)
        set(ARG_COMMAND ${name})
    endif()
    if(NOT ARG_TIMEOUT)
        set(ARG_TIMEOUT 30)
    endif()
    add_test(NAME ${name} COMMAND ${ARG_COMMAND})
    set_tests_properties(${name} PROPERTIES TIMEOUT ${ARG_TIMEOUT} LABELS "${ARG_LABELS}")
endfunction()
