include_guard(GLOBAL)
include(CTest)

option(RANGES_BUILD_REFERENCE "Build independent solutions and checker controls" ON)
option(RANGES_TEST_STUDENTS "Register unfinished student implementations" OFF)
option(RANGES_ENABLE_ASAN "Instrument safe examples" OFF)
option(RANGES_ENABLE_FRONTIER "Probe and run draft-standard examples separately" OFF)

option(RANGES_ENABLE_WARNINGS "Enable strict warnings" OFF)
option(RANGES_ENABLE_UBSAN "Enable UndefinedBehaviorSanitizer" OFF)
# CMake 4.2 does not yet map MSVC C++26. Also supports standalone units.
if(MSVC)
    set(CMAKE_CXX26_STANDARD_COMPILE_OPTION "/std:c++latest")
    set(CMAKE_CXX26_EXTENSION_COMPILE_OPTION "/std:c++latest")
    if(RANGES_ENABLE_UBSAN)
        message(FATAL_ERROR "MSVC has no UBSan; use a supported separate toolchain")
    endif()
endif()

function(ranges_configure_target target)
    set_target_properties(${target} PROPERTIES CXX_STANDARD 26 CXX_STANDARD_REQUIRED ON)
    set_target_properties(${target} PROPERTIES CXX_EXTENSIONS OFF CXX_SCAN_FOR_MODULES OFF)
    target_include_directories(${target} PRIVATE
        "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../../C01_Build_Compile_Link/exercises/include"
        "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../include"
        "${CMAKE_CURRENT_SOURCE_DIR}/include")
    if(MSVC)
        target_compile_options(${target} PRIVATE /utf-8 /EHsc /permissive- /Zc:__cplusplus)
    endif()
    if(RANGES_ENABLE_WARNINGS)
        if(MSVC)
            target_compile_options(${target} PRIVATE /W4)
        else()
            target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
        endif()
    endif()
    if(RANGES_ENABLE_UBSAN)
        target_compile_options(${target} PRIVATE -fsanitize=undefined -fno-sanitize-recover=all)
        target_link_options(${target} PRIVATE -fsanitize=undefined)
    endif()
    if(RANGES_ENABLE_ASAN)
        if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
            target_compile_options(${target} PRIVATE /fsanitize=address /Zi)
            target_link_options(${target} PRIVATE /INCREMENTAL:NO)
            get_filename_component(compiler_dir "${CMAKE_CXX_COMPILER}" DIRECTORY)
            if(CMAKE_SIZEOF_VOID_P EQUAL 8)
                set(arch x86_64)
            else()
                set(arch i386)
            endif()
            set(runtime "${compiler_dir}/clang_rt.asan_dynamic-${arch}.dll")
            if(NOT EXISTS "${runtime}")
                message(FATAL_ERROR "Matching compiler ASan runtime missing: ${runtime}")
            endif()
            add_custom_command(TARGET ${target} POST_BUILD COMMAND ${CMAKE_COMMAND} -E
                copy_if_different "${runtime}" "$<TARGET_FILE_DIR:${target}>" VERBATIM)
        elseif(NOT WIN32 AND CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
            target_compile_options(${target} PRIVATE -fsanitize=address -fno-omit-frame-pointer)
            target_link_options(${target} PRIVATE -fsanitize=address)
        else()
            message(FATAL_ERROR "Use the documented MSVC Windows or Clang/GCC Unix ASan profile")
        endif()
    endif()
endfunction()

function(ranges_add_test name)
    cmake_parse_arguments(ARG "" "TIMEOUT" "COMMAND;LABELS" ${ARGN})
    if(NOT BUILD_TESTING)
        return()
    endif()
    if(NOT ARG_COMMAND)
        set(ARG_COMMAND ${name})
    endif()
    if(NOT ARG_TIMEOUT)
        set(ARG_TIMEOUT 30)
    endif()
    add_test(NAME ${name} COMMAND ${ARG_COMMAND})
    set_tests_properties(${name} PROPERTIES TIMEOUT ${ARG_TIMEOUT} LABELS "${ARG_LABELS}")
endfunction()

function(ranges_add_observation name source)
    add_executable(${name} ${source})
    ranges_configure_target(${name})
    ranges_add_test(${name} LABELS observation)
endfunction()

function(ranges_add_exercise)
    cmake_parse_arguments(ARG "" "NAME;HEADER;CHECK;BAD_DIAGNOSTIC" "" ${ARGN})
    foreach(field NAME HEADER CHECK BAD_DIAGNOSTIC)
        if(NOT ARG_${field})
            message(FATAL_ERROR "ranges_add_exercise requires ${field}")
        endif()
    endforeach()
    set(variants student)
    if(RANGES_BUILD_REFERENCE)
        list(APPEND variants reference validation_good validation_bad)
    endif()
    foreach(variant IN LISTS variants)
        set(target "${ARG_NAME}_${variant}")
        if(variant MATCHES "^validation_(.*)")
            set(impl "validation/${CMAKE_MATCH_1}")
        else()
            set(impl "src/${variant}")
        endif()
        if(variant STREQUAL "student" AND NOT RANGES_TEST_STUDENTS)
            add_executable(${target} EXCLUDE_FROM_ALL ${ARG_CHECK})
        else()
            add_executable(${target} ${ARG_CHECK})
        endif()
        ranges_configure_target(${target})
        target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/${impl}"
            "${CMAKE_CURRENT_SOURCE_DIR}/checks")
        if(NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${impl}/${ARG_HEADER}")
            message(FATAL_ERROR "Missing independent implementation: ${impl}/${ARG_HEADER}")
        endif()
        if(variant STREQUAL "student")
            set_property(GLOBAL APPEND PROPERTY C06_STUDENT_TARGETS ${target})
            if(RANGES_TEST_STUDENTS)
                ranges_add_test(${target} LABELS student)
            endif()
        elseif(variant STREQUAL "validation_bad")
            ranges_add_test(${target}_rejected COMMAND ${CMAKE_COMMAND}
                "-DEXECUTABLE=$<TARGET_FILE:${target}>" "-DEXPECTED_TEXT=${ARG_BAD_DIAGNOSTIC}"
                -P "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../../C05_Data_Representation_Standard_Facilities/exercises/cmake/expect_failure.cmake" LABELS negative)
        elseif(variant STREQUAL "reference")
            ranges_add_test(${target} LABELS reference)
        else()
            ranges_add_test(${target} LABELS validation)
        endif()
    endforeach()
    # Old build entry now selects the independent student driver.
    add_custom_target(${ARG_NAME} DEPENDS ${ARG_NAME}_student)
endfunction()
