cmake_minimum_required(VERSION 3.28)
project(c02_no_student_target LANGUAGES CXX)
add_executable(plain_target main.cpp)
target_compile_features(plain_target PRIVATE cxx_std_23)
set_target_properties(plain_target PROPERTIES CXX_SCAN_FOR_MODULES OFF)
if(MSVC)
    target_compile_options(plain_target PRIVATE /showIncludes /utf-8)
else()
    target_compile_options(plain_target PRIVATE -H)
endif()
