include_guard(GLOBAL)

if(NOT C18_ENABLE_LUA)
  return()
endif()

find_package(Lua 5.4.9 EXACT REQUIRED)

if(Lua_FOUND AND NOT TARGET Lua::Lua)
  add_library(Lua::Lua INTERFACE IMPORTED)
  set_target_properties(Lua::Lua PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${LUA_INCLUDE_DIR}"
    INTERFACE_LINK_LIBRARIES "${LUA_LIBRARIES}")
endif()

if(NOT TARGET c18_lua_backend)
  add_library(c18_lua_backend STATIC
    "${C18_EXERCISES}/backends/lua_backend.cpp"
    "${C18_EXERCISES}/backends/lua_boundary.c")
  c18_target(c18_lua_backend)
  target_include_directories(c18_lua_backend PUBLIC "${C18_EXERCISES}/backends")
  target_link_libraries(c18_lua_backend PUBLIC Lua::Lua)
endif()

function(c18_lua_exercise name)
  cmake_parse_arguments(ARG "" "EXPECT" "" ${ARGN})
  if(NOT ARG_EXPECT)
    message(FATAL_ERROR "c18_lua_exercise requires EXPECT")
  endif()
  set(variants student)
  if(C18_BUILD_REFERENCE)
    list(APPEND variants reference good bad)
  endif()
  foreach(variant IN LISTS variants)
    if(variant STREQUAL "good" OR variant STREQUAL "bad")
      set(implementation "validation/${variant}")
    else()
      set(implementation "${variant}")
    endif()
    set(target "${name}_${variant}")
    add_executable(${target} checks.cpp)
    c18_target(${target})
    target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/${implementation}")
    target_link_libraries(${target} PRIVATE c18_lua_backend)
    if(variant STREQUAL "student")
      if(C18_TEST_STUDENTS)
        c18_add_test(${target} ${target} LABELS "student;lua")
      endif()
    elseif(variant STREQUAL "bad")
      c18_add_test(${target}_rejected ${target} EXPECT_FAILURE "${ARG_EXPECT}" LABELS "checker;lua")
    else()
      c18_add_test(${target} ${target} LABELS "${variant};lua")
    endif()
  endforeach()
endfunction()
