include_guard(GLOBAL)

set_property(GLOBAL PROPERTY USE_FOLDERS ON)
set_property(GLOBAL PROPERTY PREDEFINED_TARGETS_FOLDER "_CMake")

# Call at the end of the unit, after all of its targets have been declared.
# FILES adds documentation; BROWSE is only for isolated, non-compiled inputs.
# Implementation headers belong in each target's own target_sources list.
function(learncpp_setup_ide primary)
    cmake_parse_arguments(ARG "" "" "FILES;BROWSE" ${ARGN})
    if("${primary}" STREQUAL "" AND (ARG_FILES OR ARG_BROWSE))
        message(FATAL_ERROR "FILES/BROWSE require a primary target; attach auxiliary files with target_sources")
    endif()
    get_property(targets DIRECTORY PROPERTY BUILDSYSTEM_TARGETS)
    get_filename_component(unit "${CMAKE_CURRENT_SOURCE_DIR}" NAME)
    if(unit STREQUAL "exercises")
        set(unit "_Course")
    elseif(unit STREQUAL "runtime_tests")
        set(unit "_Course/Checks")
    elseif(unit STREQUAL "benchmarks")
        set(unit "_Course/Benchmarks")
    endif()

    if(NOT "${primary}" STREQUAL "")
        if(NOT TARGET "${primary}")
            message(FATAL_ERROR "Unknown IDE primary target: ${primary}")
        endif()
        set(docs ${ARG_FILES})
        foreach(doc README.md CMakeLists.txt)
            if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${doc}")
                list(APPEND docs "${CMAKE_CURRENT_SOURCE_DIR}/${doc}")
            endif()
        endforeach()
        foreach(input IN LISTS ARG_BROWSE)
            get_filename_component(input_path "${input}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
            foreach(target IN LISTS targets)
                get_target_property(sources ${target} SOURCES)
                get_target_property(source_dir ${target} SOURCE_DIR)
                foreach(source IN LISTS sources)
                    if(source MATCHES "^\\$<")
                        continue()
                    endif()
                    get_filename_component(source_path "${source}" ABSOLUTE BASE_DIR "${source_dir}")
                    get_source_file_property(header_only "${source_path}" HEADER_FILE_ONLY)
                    if(source_path STREQUAL input_path AND source MATCHES "[.](c|cc|cpp|cxx|ixx|cppm)$" AND NOT header_only)
                        message(FATAL_ERROR "BROWSE input ${input} is compiled by ${target}; keep it in that project")
                    endif()
                endforeach()
            endforeach()
        endforeach()
        target_sources(${primary} PRIVATE ${docs} ${ARG_BROWSE})
        if(ARG_BROWSE)
            set_source_files_properties(${ARG_BROWSE} PROPERTIES HEADER_FILE_ONLY TRUE LEARNCPP_IDE_BROWSE TRUE)
            source_group(TREE "${CMAKE_CURRENT_SOURCE_DIR}" PREFIX "Experiments" FILES ${ARG_BROWSE})
        endif()
    endif()

    foreach(target IN LISTS targets)
        get_target_property(folder ${target} FOLDER)
        get_target_property(kind ${target} TYPE)
        string(TOLOWER "${target}" name)
        if(folder STREQUAL "CTestDashboardTargets")
            set(folder "_CMake/CTest")
        elseif(NOT folder)
            if(unit MATCHES "^_Course")
                if(unit STREQUAL "_Course" AND kind MATCHES "LIBRARY$")
                    set(folder "_Course/Dependencies")
                else()
                    set(folder "${unit}")
                endif()
            elseif(target STREQUAL primary OR (kind STREQUAL "EXECUTABLE" AND name MATCHES "_student$"))
                set(folder "${unit}")
            elseif(name MATCHES "reference|(^|_)answer(_|$)")
                set(folder "${unit}/Reference")
            elseif(kind MATCHES "LIBRARY$" OR kind STREQUAL "UTILITY")
                set(folder "${unit}/Support")
            elseif(name MATCHES "(^|_)(validation|good|bad|check|checked|test|negative)(_|$)")
                set(folder "${unit}/Checks")
            else()
                set(folder "${unit}/Experiments")
            endif()
        endif()
        set_property(TARGET ${target} PROPERTY FOLDER "${folder}")
        if(kind STREQUAL "EXECUTABLE")
            get_target_property(working_dir ${target} VS_DEBUGGER_WORKING_DIRECTORY)
            if(NOT working_dir)
                set_property(TARGET ${target} PROPERTY VS_DEBUGGER_WORKING_DIRECTORY "$<TARGET_FILE_DIR:${target}>")
            endif()
            if(target STREQUAL primary)
                set_property(DIRECTORY PROPERTY VS_STARTUP_PROJECT ${target})
                get_property(startup DIRECTORY "${CMAKE_SOURCE_DIR}" PROPERTY VS_STARTUP_PROJECT)
                if(NOT startup)
                    set_property(DIRECTORY "${CMAKE_SOURCE_DIR}" PROPERTY VS_STARTUP_PROJECT ${target})
                endif()
            endif()
        endif()

        get_target_property(sources ${target} SOURCES)
        get_target_property(source_dir ${target} SOURCE_DIR)
        foreach(source IN LISTS sources)
            if(source MATCHES "^\\$<" OR source MATCHES "-NOTFOUND$")
                continue()
            endif()
            get_filename_component(path "${source}" ABSOLUTE BASE_DIR "${source_dir}")
            file(RELATIVE_PATH relative "${CMAKE_CURRENT_SOURCE_DIR}" "${path}")
            if(relative MATCHES "^\\.\\./")
                source_group("Common" FILES "${path}")
            else()
                get_filename_component(parent "${relative}" DIRECTORY)
                get_source_file_property(browse "${path}" LEARNCPP_IDE_BROWSE)
                if(browse)
                    set(group "Experiments")
                elseif(relative MATCHES "(^|/)(student|starter)(/|$)")
                    set(group "Student")
                elseif(relative MATCHES "(^|/)reference(/|$)" OR relative STREQUAL "solution.cpp")
                    set(group "Reference")
                elseif(relative MATCHES "(^|/)(validation|good|bad[^/]*|checks|tests)(/|$)" OR relative MATCHES "(^|/)(checks|check_main)[.]cpp$")
                    set(group "Checks")
                elseif(relative MATCHES "(^|/)(negative|observation|unsafe|frontier)(/|$)")
                    set(group "Experiments")
                elseif(relative MATCHES "[.](md|cmake|py|ps1|json|txt|proto|in)$")
                    set(group "Docs")
                elseif(relative MATCHES "[.](h|hpp|hxx)$")
                    set(group "Headers")
                else()
                    set(group "Sources")
                endif()
                if(parent)
                    string(REPLACE "/" "\\" parent "${parent}")
                    string(APPEND group "\\${parent}")
                endif()
                source_group("${group}" FILES "${path}")
            endif()
        endforeach()
    endforeach()
endfunction()
