include_guard(GLOBAL)
include(CTest)
find_package(Python3 REQUIRED COMPONENTS Interpreter)
get_filename_component(C16_EXERCISES "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
get_filename_component(C16_COURSE "${C16_EXERCISES}/.." ABSOLUTE)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_SCAN_FOR_MODULES OFF)
set(CMAKE_AUTOMOC ON)
option(C16_BUILD_REFERENCE "Build independent answers and checker controls" ON)
option(C16_TEST_STUDENTS "Run student exercises (unfinished exercises fail)" OFF)

function(c16_target target)
  if(ARGN)
    find_package(Qt6 6.9.2 EXACT REQUIRED COMPONENTS ${ARGN})
    foreach(component IN LISTS ARGN)
      target_link_libraries(${target} PRIVATE Qt6::${component})
    endforeach()
  endif()
  target_include_directories(${target} PRIVATE "${C16_EXERCISES}/include")
  target_compile_features(${target} PRIVATE cxx_std_23)
  if(MSVC)
    target_compile_options(${target} PRIVATE /utf-8 /W4 /permissive- /Zc:__cplusplus /EHsc)
    target_compile_definitions(${target} PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
  else()
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
  endif()
endfunction()

function(c16_add_test name target)
  cmake_parse_arguments(ARG "ALLOW_SKIP" "TIMEOUT;EXPECT_FAILURE" "ARGS;LABELS" ${ARGN})
  if(NOT ARG_TIMEOUT)
    set(ARG_TIMEOUT 30)
  endif()
  if(BUILD_TESTING)
    set(extra)
    if(ARG_ALLOW_SKIP)
      list(APPEND extra --allow-skip)
    endif()
    if(ARG_EXPECT_FAILURE)
      list(APPEND extra --expect-failure "${ARG_EXPECT_FAILURE}")
    endif()
    add_test(NAME ${name} COMMAND "${Python3_EXECUTABLE}" "${C16_COURSE}/tools/run_check.py"
      --timeout "${ARG_TIMEOUT}" ${extra} -- "$<TARGET_FILE:${target}>" ${ARG_ARGS})
    math(EXPR outer_timeout "${ARG_TIMEOUT}+15")
    file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/test-tmp")
    set_tests_properties(${name} PROPERTIES TIMEOUT ${outer_timeout} LABELS "${ARG_LABELS}"
      ENVIRONMENT "QT_QPA_PLATFORM=offscreen;QT_QUICK_BACKEND=software;QT_MEDIA_BACKEND=ffmpeg;TEMP=${CMAKE_CURRENT_BINARY_DIR}/test-tmp;TMP=${CMAKE_CURRENT_BINARY_DIR}/test-tmp;TMPDIR=${CMAKE_CURRENT_BINARY_DIR}/test-tmp")
    if(ARG_ALLOW_SKIP)
      set_tests_properties(${name} PROPERTIES SKIP_RETURN_CODE 77)
    endif()
    if(WIN32 AND TARGET Qt6::qmake)
      get_target_property(qmake_path Qt6::qmake IMPORTED_LOCATION)
      get_filename_component(qt_bin "${qmake_path}" DIRECTORY)
      set_property(TEST ${name} APPEND PROPERTY ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:${qt_bin}")
    endif()
  endif()
endfunction()

function(c16_exercise name)
  cmake_parse_arguments(ARG "" "EXPECT" "QT" ${ARGN})
  if(NOT ARG_EXPECT)
    set(ARG_EXPECT "check failed:")
  endif()
  set(variants student)
  if(C16_BUILD_REFERENCE)
    list(APPEND variants reference good bad)
  endif()
  foreach(variant IN LISTS variants)
    set(target "${name}_${variant}")
    add_executable(${target} checks.cpp "${variant}/solution.hpp")
    c16_target(${target} ${ARG_QT})
    target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/${variant}")
    if(variant STREQUAL "student")
      if(C16_TEST_STUDENTS)
        c16_add_test(${target} ${target} LABELS student)
      endif()
    elseif(variant STREQUAL "bad")
      c16_add_test(${target}_rejected ${target} EXPECT_FAILURE "${ARG_EXPECT}" LABELS checker)
    else()
      c16_add_test(${target} ${target} LABELS "${variant}")
    endif()
  endforeach()
endfunction()
